template: |
  ## What's Changed

  $CHANGES
name-template: 'v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'task'
      - 'refactor'
  - title: '📚 Documentation'
    labels:
      - 'docs'
  - title: '🥂 Improvements'
    labels:
      - 'performance'
      - 'test'

  - title: '🍏 CI & Build'
    labels:
      - 'ci'
      - 'build'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
