/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ReadinessResponse } from '../models';
/**
 * HealthApi - axios parameter creator
 * @export
 */
export const HealthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Note: OpenAPI documentation for these endpoints can be found in the `openapi.rs` file  Handles the `/health` endpoint.  Returns an `HttpResponse` with a status of `200 OK` and a body of `\"OK\"`. This endpoint is used for liveness probes in container orchestration platforms.
         * @summary Health routes implementation
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        health: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns 200 OK if the service is ready to accept traffic, or 503 Service Unavailable if not. This endpoint is used for readiness probes in container orchestration platforms like AWS ECS or Kubernetes.  ## Health Check Components  - **System**: File descriptor usage, CLOSE_WAIT socket count - **Redis**: Primary and reader pool connectivity - **Queue**: Queue\'s Redis connections (separate from app\'s Redis) - **Plugins**: Plugin pool health, circuit breaker state, and connection metrics (if enabled)  ## Status Levels  - `healthy`: All components operational - `degraded`: Some components degraded but service can function (e.g., reader pool down) - `unhealthy`: Critical components failed, service unavailable  ## Plugin Connection Metrics  When plugins are enabled, the following connection metrics are exposed:  - `shared_socket_available_slots`: Number of additional concurrent plugin executions that can start - `shared_socket_active_connections`: Current number of active plugin execution connections - `shared_socket_registered_executions`: Number of plugin executions currently registered (awaiting response) - `connection_pool_available_slots`: Available connections to the pool server - `connection_pool_active_connections`: Active connections to the pool server  These metrics help diagnose connection pool exhaustion and plugin capacity issues.  ## Caching  Health check results are cached for 10 seconds to prevent excessive load from frequent health checks. Multiple requests within the TTL return the same cached response.
         * @summary Readiness endpoint that checks system resources, Redis, Queue, and plugins.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readiness: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/ready`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HealthApi - functional programming interface
 * @export
 */
export const HealthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HealthApiAxiosParamCreator(configuration)
    return {
        /**
         * Note: OpenAPI documentation for these endpoints can be found in the `openapi.rs` file  Handles the `/health` endpoint.  Returns an `HttpResponse` with a status of `200 OK` and a body of `\"OK\"`. This endpoint is used for liveness probes in container orchestration platforms.
         * @summary Health routes implementation
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async health(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.health(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HealthApi.health']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns 200 OK if the service is ready to accept traffic, or 503 Service Unavailable if not. This endpoint is used for readiness probes in container orchestration platforms like AWS ECS or Kubernetes.  ## Health Check Components  - **System**: File descriptor usage, CLOSE_WAIT socket count - **Redis**: Primary and reader pool connectivity - **Queue**: Queue\'s Redis connections (separate from app\'s Redis) - **Plugins**: Plugin pool health, circuit breaker state, and connection metrics (if enabled)  ## Status Levels  - `healthy`: All components operational - `degraded`: Some components degraded but service can function (e.g., reader pool down) - `unhealthy`: Critical components failed, service unavailable  ## Plugin Connection Metrics  When plugins are enabled, the following connection metrics are exposed:  - `shared_socket_available_slots`: Number of additional concurrent plugin executions that can start - `shared_socket_active_connections`: Current number of active plugin execution connections - `shared_socket_registered_executions`: Number of plugin executions currently registered (awaiting response) - `connection_pool_available_slots`: Available connections to the pool server - `connection_pool_active_connections`: Active connections to the pool server  These metrics help diagnose connection pool exhaustion and plugin capacity issues.  ## Caching  Health check results are cached for 10 seconds to prevent excessive load from frequent health checks. Multiple requests within the TTL return the same cached response.
         * @summary Readiness endpoint that checks system resources, Redis, Queue, and plugins.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async readiness(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ReadinessResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.readiness(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HealthApi.readiness']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HealthApi - factory interface
 * @export
 */
export const HealthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HealthApiFp(configuration)
    return {
        /**
         * Note: OpenAPI documentation for these endpoints can be found in the `openapi.rs` file  Handles the `/health` endpoint.  Returns an `HttpResponse` with a status of `200 OK` and a body of `\"OK\"`. This endpoint is used for liveness probes in container orchestration platforms.
         * @summary Health routes implementation
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        health(options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.health(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns 200 OK if the service is ready to accept traffic, or 503 Service Unavailable if not. This endpoint is used for readiness probes in container orchestration platforms like AWS ECS or Kubernetes.  ## Health Check Components  - **System**: File descriptor usage, CLOSE_WAIT socket count - **Redis**: Primary and reader pool connectivity - **Queue**: Queue\'s Redis connections (separate from app\'s Redis) - **Plugins**: Plugin pool health, circuit breaker state, and connection metrics (if enabled)  ## Status Levels  - `healthy`: All components operational - `degraded`: Some components degraded but service can function (e.g., reader pool down) - `unhealthy`: Critical components failed, service unavailable  ## Plugin Connection Metrics  When plugins are enabled, the following connection metrics are exposed:  - `shared_socket_available_slots`: Number of additional concurrent plugin executions that can start - `shared_socket_active_connections`: Current number of active plugin execution connections - `shared_socket_registered_executions`: Number of plugin executions currently registered (awaiting response) - `connection_pool_available_slots`: Available connections to the pool server - `connection_pool_active_connections`: Active connections to the pool server  These metrics help diagnose connection pool exhaustion and plugin capacity issues.  ## Caching  Health check results are cached for 10 seconds to prevent excessive load from frequent health checks. Multiple requests within the TTL return the same cached response.
         * @summary Readiness endpoint that checks system resources, Redis, Queue, and plugins.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readiness(options?: RawAxiosRequestConfig): AxiosPromise<ReadinessResponse> {
            return localVarFp.readiness(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HealthApi - object-oriented interface
 * @export
 * @class HealthApi
 * @extends {BaseAPI}
 */
export class HealthApi extends BaseAPI {
    /**
     * Note: OpenAPI documentation for these endpoints can be found in the `openapi.rs` file  Handles the `/health` endpoint.  Returns an `HttpResponse` with a status of `200 OK` and a body of `\"OK\"`. This endpoint is used for liveness probes in container orchestration platforms.
     * @summary Health routes implementation
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HealthApi
     */
    public health(options?: RawAxiosRequestConfig) {
        return HealthApiFp(this.configuration).health(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns 200 OK if the service is ready to accept traffic, or 503 Service Unavailable if not. This endpoint is used for readiness probes in container orchestration platforms like AWS ECS or Kubernetes.  ## Health Check Components  - **System**: File descriptor usage, CLOSE_WAIT socket count - **Redis**: Primary and reader pool connectivity - **Queue**: Queue\'s Redis connections (separate from app\'s Redis) - **Plugins**: Plugin pool health, circuit breaker state, and connection metrics (if enabled)  ## Status Levels  - `healthy`: All components operational - `degraded`: Some components degraded but service can function (e.g., reader pool down) - `unhealthy`: Critical components failed, service unavailable  ## Plugin Connection Metrics  When plugins are enabled, the following connection metrics are exposed:  - `shared_socket_available_slots`: Number of additional concurrent plugin executions that can start - `shared_socket_active_connections`: Current number of active plugin execution connections - `shared_socket_registered_executions`: Number of plugin executions currently registered (awaiting response) - `connection_pool_available_slots`: Available connections to the pool server - `connection_pool_active_connections`: Active connections to the pool server  These metrics help diagnose connection pool exhaustion and plugin capacity issues.  ## Caching  Health check results are cached for 10 seconds to prevent excessive load from frequent health checks. Multiple requests within the TTL return the same cached response.
     * @summary Readiness endpoint that checks system resources, Redis, Queue, and plugins.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HealthApi
     */
    public readiness(options?: RawAxiosRequestConfig) {
        return HealthApiFp(this.configuration).readiness(options).then((request) => request(this.axios, this.basePath));
    }
}

