/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponsePaginatedResultPluginModel } from '../models';
// @ts-ignore
import type { ApiResponsePluginHandlerError } from '../models';
// @ts-ignore
import type { ApiResponseString } from '../models';
// @ts-ignore
import type { ApiResponseValue } from '../models';
// @ts-ignore
import type { PluginCallRequest } from '../models';
/**
 * PluginsApi - axios parameter creator
 * @export
 */
export const PluginsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Logs and traces are only returned when the plugin is configured with `emit_logs` / `emit_traces`. Plugin-provided errors are normalized into a consistent payload (`code`, `details`) and a derived message so downstream clients receive a stable shape regardless of how the handler threw.  The endpoint supports wildcard route routing, allowing plugins to implement custom routing logic: - `/api/v1/plugins/{plugin_id}/call` - Default endpoint (route = \"\") - `/api/v1/plugins/{plugin_id}/call?route=/verify` - Custom route via query parameter - `/api/v1/plugins/{plugin_id}/call/verify` - Custom route via URL path (route = \"/verify\")  The route is passed to the plugin handler via the `context.route` field. You can specify a custom route either by appending it to the URL path or by using the `route` query parameter.
         * @summary Execute a plugin with optional wildcard route routing
         * @param {string} pluginId The unique identifier of the plugin
         * @param {PluginCallRequest} pluginCallRequest 
         * @param {string} [route] Optional route suffix for custom routing (e.g., \&#39;/verify\&#39;). Alternative to appending the route to the URL path.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        callPlugin: async (pluginId: string, pluginCallRequest: PluginCallRequest, route?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pluginId' is not null or undefined
            assertParamExists('callPlugin', 'pluginId', pluginId)
            // verify required parameter 'pluginCallRequest' is not null or undefined
            assertParamExists('callPlugin', 'pluginCallRequest', pluginCallRequest)
            const localVarPath = `/api/v1/plugins/{plugin_id}/call`
                .replace(`{${"plugin_id"}}`, encodeURIComponent(String(pluginId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer_auth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (route !== undefined) {
                localVarQueryParameter['route'] = route;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(pluginCallRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This endpoint is disabled by default. To enable it for a given plugin, set `allow_get_invocation: true` in the plugin configuration.  When invoked via GET: - `params` is an empty object (`{}`) - query parameters are passed to the plugin handler via `context.query` - wildcard route routing is supported the same way as POST (see `doc_call_plugin`) - Use the `route` query parameter or append the route to the URL path
         * @summary Execute a plugin via GET (must be enabled per plugin)
         * @param {string} pluginId The unique identifier of the plugin
         * @param {string} [route] Optional route suffix for custom routing (e.g., \&#39;/verify\&#39;). Alternative to appending the route to the URL path.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        callPluginGet: async (pluginId: string, route?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pluginId' is not null or undefined
            assertParamExists('callPluginGet', 'pluginId', pluginId)
            const localVarPath = `/api/v1/plugins/{plugin_id}/call`
                .replace(`{${"plugin_id"}}`, encodeURIComponent(String(pluginId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer_auth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (route !== undefined) {
                localVarQueryParameter['route'] = route;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List plugins.
         * @param {number} [page] Page number for pagination (starts at 1)
         * @param {number} [perPage] Number of items per page (default: 10)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPlugins: async (page?: number, perPage?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/plugins`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer_auth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['per_page'] = perPage;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PluginsApi - functional programming interface
 * @export
 */
export const PluginsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PluginsApiAxiosParamCreator(configuration)
    return {
        /**
         * Logs and traces are only returned when the plugin is configured with `emit_logs` / `emit_traces`. Plugin-provided errors are normalized into a consistent payload (`code`, `details`) and a derived message so downstream clients receive a stable shape regardless of how the handler threw.  The endpoint supports wildcard route routing, allowing plugins to implement custom routing logic: - `/api/v1/plugins/{plugin_id}/call` - Default endpoint (route = \"\") - `/api/v1/plugins/{plugin_id}/call?route=/verify` - Custom route via query parameter - `/api/v1/plugins/{plugin_id}/call/verify` - Custom route via URL path (route = \"/verify\")  The route is passed to the plugin handler via the `context.route` field. You can specify a custom route either by appending it to the URL path or by using the `route` query parameter.
         * @summary Execute a plugin with optional wildcard route routing
         * @param {string} pluginId The unique identifier of the plugin
         * @param {PluginCallRequest} pluginCallRequest 
         * @param {string} [route] Optional route suffix for custom routing (e.g., \&#39;/verify\&#39;). Alternative to appending the route to the URL path.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async callPlugin(pluginId: string, pluginCallRequest: PluginCallRequest, route?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseValue>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.callPlugin(pluginId, pluginCallRequest, route, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PluginsApi.callPlugin']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * This endpoint is disabled by default. To enable it for a given plugin, set `allow_get_invocation: true` in the plugin configuration.  When invoked via GET: - `params` is an empty object (`{}`) - query parameters are passed to the plugin handler via `context.query` - wildcard route routing is supported the same way as POST (see `doc_call_plugin`) - Use the `route` query parameter or append the route to the URL path
         * @summary Execute a plugin via GET (must be enabled per plugin)
         * @param {string} pluginId The unique identifier of the plugin
         * @param {string} [route] Optional route suffix for custom routing (e.g., \&#39;/verify\&#39;). Alternative to appending the route to the URL path.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async callPluginGet(pluginId: string, route?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseValue>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.callPluginGet(pluginId, route, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PluginsApi.callPluginGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List plugins.
         * @param {number} [page] Page number for pagination (starts at 1)
         * @param {number} [perPage] Number of items per page (default: 10)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listPlugins(page?: number, perPage?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePaginatedResultPluginModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listPlugins(page, perPage, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PluginsApi.listPlugins']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PluginsApi - factory interface
 * @export
 */
export const PluginsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PluginsApiFp(configuration)
    return {
        /**
         * Logs and traces are only returned when the plugin is configured with `emit_logs` / `emit_traces`. Plugin-provided errors are normalized into a consistent payload (`code`, `details`) and a derived message so downstream clients receive a stable shape regardless of how the handler threw.  The endpoint supports wildcard route routing, allowing plugins to implement custom routing logic: - `/api/v1/plugins/{plugin_id}/call` - Default endpoint (route = \"\") - `/api/v1/plugins/{plugin_id}/call?route=/verify` - Custom route via query parameter - `/api/v1/plugins/{plugin_id}/call/verify` - Custom route via URL path (route = \"/verify\")  The route is passed to the plugin handler via the `context.route` field. You can specify a custom route either by appending it to the URL path or by using the `route` query parameter.
         * @summary Execute a plugin with optional wildcard route routing
         * @param {string} pluginId The unique identifier of the plugin
         * @param {PluginCallRequest} pluginCallRequest 
         * @param {string} [route] Optional route suffix for custom routing (e.g., \&#39;/verify\&#39;). Alternative to appending the route to the URL path.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        callPlugin(pluginId: string, pluginCallRequest: PluginCallRequest, route?: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseValue> {
            return localVarFp.callPlugin(pluginId, pluginCallRequest, route, options).then((request) => request(axios, basePath));
        },
        /**
         * This endpoint is disabled by default. To enable it for a given plugin, set `allow_get_invocation: true` in the plugin configuration.  When invoked via GET: - `params` is an empty object (`{}`) - query parameters are passed to the plugin handler via `context.query` - wildcard route routing is supported the same way as POST (see `doc_call_plugin`) - Use the `route` query parameter or append the route to the URL path
         * @summary Execute a plugin via GET (must be enabled per plugin)
         * @param {string} pluginId The unique identifier of the plugin
         * @param {string} [route] Optional route suffix for custom routing (e.g., \&#39;/verify\&#39;). Alternative to appending the route to the URL path.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        callPluginGet(pluginId: string, route?: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseValue> {
            return localVarFp.callPluginGet(pluginId, route, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List plugins.
         * @param {number} [page] Page number for pagination (starts at 1)
         * @param {number} [perPage] Number of items per page (default: 10)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPlugins(page?: number, perPage?: number, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePaginatedResultPluginModel> {
            return localVarFp.listPlugins(page, perPage, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PluginsApi - object-oriented interface
 * @export
 * @class PluginsApi
 * @extends {BaseAPI}
 */
export class PluginsApi extends BaseAPI {
    /**
     * Logs and traces are only returned when the plugin is configured with `emit_logs` / `emit_traces`. Plugin-provided errors are normalized into a consistent payload (`code`, `details`) and a derived message so downstream clients receive a stable shape regardless of how the handler threw.  The endpoint supports wildcard route routing, allowing plugins to implement custom routing logic: - `/api/v1/plugins/{plugin_id}/call` - Default endpoint (route = \"\") - `/api/v1/plugins/{plugin_id}/call?route=/verify` - Custom route via query parameter - `/api/v1/plugins/{plugin_id}/call/verify` - Custom route via URL path (route = \"/verify\")  The route is passed to the plugin handler via the `context.route` field. You can specify a custom route either by appending it to the URL path or by using the `route` query parameter.
     * @summary Execute a plugin with optional wildcard route routing
     * @param {string} pluginId The unique identifier of the plugin
     * @param {PluginCallRequest} pluginCallRequest 
     * @param {string} [route] Optional route suffix for custom routing (e.g., \&#39;/verify\&#39;). Alternative to appending the route to the URL path.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PluginsApi
     */
    public callPlugin(pluginId: string, pluginCallRequest: PluginCallRequest, route?: string, options?: RawAxiosRequestConfig) {
        return PluginsApiFp(this.configuration).callPlugin(pluginId, pluginCallRequest, route, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This endpoint is disabled by default. To enable it for a given plugin, set `allow_get_invocation: true` in the plugin configuration.  When invoked via GET: - `params` is an empty object (`{}`) - query parameters are passed to the plugin handler via `context.query` - wildcard route routing is supported the same way as POST (see `doc_call_plugin`) - Use the `route` query parameter or append the route to the URL path
     * @summary Execute a plugin via GET (must be enabled per plugin)
     * @param {string} pluginId The unique identifier of the plugin
     * @param {string} [route] Optional route suffix for custom routing (e.g., \&#39;/verify\&#39;). Alternative to appending the route to the URL path.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PluginsApi
     */
    public callPluginGet(pluginId: string, route?: string, options?: RawAxiosRequestConfig) {
        return PluginsApiFp(this.configuration).callPluginGet(pluginId, route, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List plugins.
     * @param {number} [page] Page number for pagination (starts at 1)
     * @param {number} [perPage] Number of items per page (default: 10)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PluginsApi
     */
    public listPlugins(page?: number, perPage?: number, options?: RawAxiosRequestConfig) {
        return PluginsApiFp(this.configuration).listPlugins(page, perPage, options).then((request) => request(this.axios, this.basePath));
    }
}

