/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiResponseDeletePendingTransactionsResponseData } from './api-response-delete-pending-transactions-response-data';
// May contain unused imports in some cases
// @ts-ignore
import type { PaginationMeta } from './pagination-meta';

/**
 * 
 * @export
 * @interface ApiResponseDeletePendingTransactionsResponse
 */
export interface ApiResponseDeletePendingTransactionsResponse {
    /**
     * 
     * @type {ApiResponseDeletePendingTransactionsResponseData}
     * @memberof ApiResponseDeletePendingTransactionsResponse
     */
    'data'?: ApiResponseDeletePendingTransactionsResponseData;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseDeletePendingTransactionsResponse
     */
    'error'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof ApiResponseDeletePendingTransactionsResponse
     */
    'pagination'?: PaginationMeta;
    /**
     * 
     * @type {boolean}
     * @memberof ApiResponseDeletePendingTransactionsResponse
     */
    'success': boolean;
}

