/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SignerConfigResponse } from './signer-config-response';
// May contain unused imports in some cases
// @ts-ignore
import type { SignerType } from './signer-type';

/**
 * 
 * @export
 * @interface ApiResponseSignerResponseData
 */
export interface ApiResponseSignerResponseData {
    /**
     * Non-secret configuration details
     * @type {SignerConfigResponse}
     * @memberof ApiResponseSignerResponseData
     */
    'config': SignerConfigResponse;
    /**
     * The unique identifier of the signer
     * @type {string}
     * @memberof ApiResponseSignerResponseData
     */
    'id': string;
    /**
     * The type of signer (local, aws_kms, google_cloud_kms, vault, etc.)
     * @type {SignerType}
     * @memberof ApiResponseSignerResponseData
     */
    'type': SignerType;
}



