/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * The OpenZeppelin Relayer API provides endpoints for managing, monitoring, and interacting with relayers. It enables developers to relay and manage blockchain transactions across EVM and non-EVM networks, making it ideal for dApps and backend services that require secure and scalable transaction infrastructure.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiResponseRelayerStatusDataOneOf1
 */
export interface ApiResponseRelayerStatusDataOneOf1 {
    /**
     * 
     * @type {string}
     * @memberof ApiResponseRelayerStatusDataOneOf1
     */
    'balance': string;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseRelayerStatusDataOneOf1
     */
    'last_confirmed_transaction_timestamp'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseRelayerStatusDataOneOf1
     */
    'network_type': ApiResponseRelayerStatusDataOneOf1NetworkTypeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof ApiResponseRelayerStatusDataOneOf1
     */
    'paused': boolean;
    /**
     * 
     * @type {number}
     * @memberof ApiResponseRelayerStatusDataOneOf1
     */
    'pending_transactions_count': number;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseRelayerStatusDataOneOf1
     */
    'sequence_number': string;
    /**
     * 
     * @type {boolean}
     * @memberof ApiResponseRelayerStatusDataOneOf1
     */
    'system_disabled': boolean;
}

/**
    * @export
    * @enum {string}
    */
export enum ApiResponseRelayerStatusDataOneOf1NetworkTypeEnum {
    STELLAR = 'stellar'
}


