/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DisabledReason } from './disabled-reason';
// May contain unused imports in some cases
// @ts-ignore
import type { MaskedRpcConfig } from './masked-rpc-config';
// May contain unused imports in some cases
// @ts-ignore
import type { RelayerNetworkPolicyResponse } from './relayer-network-policy-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RelayerNetworkType } from './relayer-network-type';

/**
 * Relayer response model for API endpoints
 * @export
 * @interface ApiResponseRelayerResponseData
 */
export interface ApiResponseRelayerResponseData {
    /**
     * 
     * @type {string}
     * @memberof ApiResponseRelayerResponseData
     */
    'address'?: string;
    /**
     * Custom RPC URLs with sensitive path/query parameters masked for security. The domain is visible to identify providers (e.g., Alchemy, Infura) but API keys embedded in paths are hidden.
     * @type {Array<MaskedRpcConfig>}
     * @memberof ApiResponseRelayerResponseData
     */
    'custom_rpc_urls'?: Array<MaskedRpcConfig>;
    /**
     * 
     * @type {DisabledReason}
     * @memberof ApiResponseRelayerResponseData
     */
    'disabled_reason'?: DisabledReason;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseRelayerResponseData
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseRelayerResponseData
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseRelayerResponseData
     */
    'network': string;
    /**
     * 
     * @type {RelayerNetworkType}
     * @memberof ApiResponseRelayerResponseData
     */
    'network_type': RelayerNetworkType;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseRelayerResponseData
     */
    'notification_id'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApiResponseRelayerResponseData
     */
    'paused': boolean;
    /**
     * Policies without redundant network_type tag - network type is available at top level Only included if user explicitly provided policies (not shown for empty/default policies)
     * @type {RelayerNetworkPolicyResponse}
     * @memberof ApiResponseRelayerResponseData
     */
    'policies'?: RelayerNetworkPolicyResponse;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseRelayerResponseData
     */
    'signer_id': string;
    /**
     * 
     * @type {boolean}
     * @memberof ApiResponseRelayerResponseData
     */
    'system_disabled'?: boolean;
}



