/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiResponseNotificationResponseData } from './api-response-notification-response-data';
// May contain unused imports in some cases
// @ts-ignore
import type { PaginationMeta } from './pagination-meta';

/**
 * 
 * @export
 * @interface ApiResponseVecNotificationResponse
 */
export interface ApiResponseVecNotificationResponse {
    /**
     * 
     * @type {Array<ApiResponseNotificationResponseData>}
     * @memberof ApiResponseVecNotificationResponse
     */
    'data'?: Array<ApiResponseNotificationResponseData>;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseVecNotificationResponse
     */
    'error'?: string;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof ApiResponseVecNotificationResponse
     */
    'pagination'?: PaginationMeta;
    /**
     * 
     * @type {boolean}
     * @memberof ApiResponseVecNotificationResponse
     */
    'success': boolean;
}

