/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiResponseRelayerStatusData } from './api-response-relayer-status-data';
// May contain unused imports in some cases
// @ts-ignore
import type { PaginationMeta } from './pagination-meta';
// May contain unused imports in some cases
// @ts-ignore
import type { PluginMetadata } from './plugin-metadata';

/**
 * 
 * @export
 * @interface ApiResponseRelayerStatus
 */
export interface ApiResponseRelayerStatus {
    /**
     * 
     * @type {ApiResponseRelayerStatusData}
     * @memberof ApiResponseRelayerStatus
     */
    'data'?: ApiResponseRelayerStatusData;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseRelayerStatus
     */
    'error'?: string;
    /**
     * 
     * @type {PluginMetadata}
     * @memberof ApiResponseRelayerStatus
     */
    'metadata'?: PluginMetadata;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof ApiResponseRelayerStatus
     */
    'pagination'?: PaginationMeta;
    /**
     * 
     * @type {boolean}
     * @memberof ApiResponseRelayerStatus
     */
    'success': boolean;
}

