/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiResponseRelayerStatusDataOneOf } from './api-response-relayer-status-data-one-of';
// May contain unused imports in some cases
// @ts-ignore
import type { ApiResponseRelayerStatusDataOneOf1 } from './api-response-relayer-status-data-one-of1';
// May contain unused imports in some cases
// @ts-ignore
import type { ApiResponseRelayerStatusDataOneOf2 } from './api-response-relayer-status-data-one-of2';

/**
 * @type ApiResponseRelayerStatusData
 * Relayer status with runtime information
 * @export
 */
export type ApiResponseRelayerStatusData = ApiResponseRelayerStatusDataOneOf | ApiResponseRelayerStatusDataOneOf1 | ApiResponseRelayerStatusDataOneOf2;


