/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiResponsePluginCallResponseData } from './api-response-plugin-call-response-data';

/**
 * 
 * @export
 * @interface ApiResponsePluginCallResponse
 */
export interface ApiResponsePluginCallResponse {
    /**
     * 
     * @type {ApiResponsePluginCallResponseData}
     * @memberof ApiResponsePluginCallResponse
     */
    'data': ApiResponsePluginCallResponseData;
    /**
     * 
     * @type {string}
     * @memberof ApiResponsePluginCallResponse
     */
    'error'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApiResponsePluginCallResponse
     */
    'success': boolean;
}

