/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SignTransactionResponseSolana } from './sign-transaction-response-solana';
// May contain unused imports in some cases
// @ts-ignore
import type { SignTransactionResponseStellar } from './sign-transaction-response-stellar';

/**
 * @type ApiResponseSignTransactionResponseData
 * @export
 */
export type ApiResponseSignTransactionResponseData = Array<number> | SignTransactionResponseSolana | SignTransactionResponseStellar;


