/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiResponseSignTransactionResponseDataOneOf1
 */
export interface ApiResponseSignTransactionResponseDataOneOf1 {
    /**
     * 
     * @type {string}
     * @memberof ApiResponseSignTransactionResponseDataOneOf1
     */
    'network': ApiResponseSignTransactionResponseDataOneOf1NetworkEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum ApiResponseSignTransactionResponseDataOneOf1NetworkEnum {
    EVM = 'evm'
}


