/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiResponseSignerResponseData } from './api-response-signer-response-data';
// May contain unused imports in some cases
// @ts-ignore
import type { PaginationMeta } from './pagination-meta';
// May contain unused imports in some cases
// @ts-ignore
import type { PluginMetadata } from './plugin-metadata';

/**
 * 
 * @export
 * @interface ApiResponseVecSignerResponse
 */
export interface ApiResponseVecSignerResponse {
    /**
     * 
     * @type {Array<ApiResponseSignerResponseData>}
     * @memberof ApiResponseVecSignerResponse
     */
    'data'?: Array<ApiResponseSignerResponseData>;
    /**
     * 
     * @type {string}
     * @memberof ApiResponseVecSignerResponse
     */
    'error'?: string;
    /**
     * 
     * @type {PluginMetadata}
     * @memberof ApiResponseVecSignerResponse
     */
    'metadata'?: PluginMetadata;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof ApiResponseVecSignerResponse
     */
    'pagination'?: PaginationMeta;
    /**
     * 
     * @type {boolean}
     * @memberof ApiResponseVecSignerResponse
     */
    'success': boolean;
}

