/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Response for delete pending transactions operation
 * @export
 * @interface ApiResponseDeletePendingTransactionsResponseData
 */
export interface ApiResponseDeletePendingTransactionsResponseData {
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiResponseDeletePendingTransactionsResponseData
     */
    'failed_to_queue_transaction_ids': Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiResponseDeletePendingTransactionsResponseData
     */
    'queued_for_cancellation_transaction_ids': Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ApiResponseDeletePendingTransactionsResponseData
     */
    'total_processed': number;
}

