/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AssetSpecOneOf1
 */
export interface AssetSpecOneOf1 {
    /**
     * 
     * @type {string}
     * @memberof AssetSpecOneOf1
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof AssetSpecOneOf1
     */
    'issuer': string;
    /**
     * 
     * @type {string}
     * @memberof AssetSpecOneOf1
     */
    'type': AssetSpecOneOf1TypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum AssetSpecOneOf1TypeEnum {
    CREDIT4 = 'credit4'
}


