/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * The OpenZeppelin Relayer API provides endpoints for managing, monitoring, and interacting with relayers. It enables developers to relay and manage blockchain transactions across EVM and non-EVM networks, making it ideal for dApps and backend services that require secure and scalable transaction infrastructure.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AssetSpecOneOf } from './asset-spec-one-of';
// May contain unused imports in some cases
// @ts-ignore
import type { AssetSpecOneOf1 } from './asset-spec-one-of1';
// May contain unused imports in some cases
// @ts-ignore
import type { AssetSpecOneOfCREDIT4 } from './asset-spec-one-of-credit4';

/**
 * @type AssetSpec
 * @export
 */
export type AssetSpec = AssetSpecOneOf | AssetSpecOneOf1 | string;


