/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AssetSpecOneOf } from './asset-spec-one-of';
// May contain unused imports in some cases
// @ts-ignore
import type { AssetSpecOneOf1 } from './asset-spec-one-of1';
// May contain unused imports in some cases
// @ts-ignore
import type { AssetSpecOneOf2 } from './asset-spec-one-of2';

/**
 * @type AssetSpec
 * @export
 */
export type AssetSpec = AssetSpecOneOf | AssetSpecOneOf1 | AssetSpecOneOf2;


