/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AssetSpecOneOf2
 */
export interface AssetSpecOneOf2 {
    /**
     * 
     * @type {string}
     * @memberof AssetSpecOneOf2
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof AssetSpecOneOf2
     */
    'issuer': string;
    /**
     * 
     * @type {string}
     * @memberof AssetSpecOneOf2
     */
    'type': AssetSpecOneOf2TypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum AssetSpecOneOf2TypeEnum {
    CREDIT12 = 'credit12'
}


