/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Use specific addresses for authorization
 * @export
 * @interface AuthSpecOneOf2
 */
export interface AuthSpecOneOf2 {
    /**
     * 
     * @type {Array<string>}
     * @memberof AuthSpecOneOf2
     */
    'signers': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof AuthSpecOneOf2
     */
    'type': AuthSpecOneOf2TypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum AuthSpecOneOf2TypeEnum {
    ADDRESSES = 'addresses'
}


