/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthSpecOneOf } from './auth-spec-one-of';
// May contain unused imports in some cases
// @ts-ignore
import type { AuthSpecOneOf1 } from './auth-spec-one-of1';
// May contain unused imports in some cases
// @ts-ignore
import type { AuthSpecOneOf2 } from './auth-spec-one-of2';
// May contain unused imports in some cases
// @ts-ignore
import type { AuthSpecOneOf3 } from './auth-spec-one-of3';

/**
 * @type AuthSpec
 * Authorization specification for Soroban operations
 * @export
 */
export type AuthSpec = AuthSpecOneOf | AuthSpecOneOf1 | AuthSpecOneOf2 | AuthSpecOneOf3;


