/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * CDP signer configuration for API requests
 * @export
 * @interface CdpSignerRequestConfig
 */
export interface CdpSignerRequestConfig {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof CdpSignerRequestConfig
     */
    'account_address': string;
    /**
     * 
     * @type {string}
     * @memberof CdpSignerRequestConfig
     */
    'api_key_id': string;
    /**
     * 
     * @type {string}
     * @memberof CdpSignerRequestConfig
     */
    'api_key_secret': string;
    /**
     * 
     * @type {string}
     * @memberof CdpSignerRequestConfig
     */
    'wallet_secret': string;
}

