/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PluginHealth } from './plugin-health';
// May contain unused imports in some cases
// @ts-ignore
import type { QueueHealth } from './queue-health';
// May contain unused imports in some cases
// @ts-ignore
import type { RedisHealth } from './redis-health';
// May contain unused imports in some cases
// @ts-ignore
import type { SystemHealth } from './system-health';

/**
 * All health check components.
 * @export
 * @interface Components
 */
export interface Components {
    /**
     * 
     * @type {PluginHealth}
     * @memberof Components
     */
    'plugins'?: PluginHealth;
    /**
     * 
     * @type {QueueHealth}
     * @memberof Components
     */
    'queue': QueueHealth;
    /**
     * 
     * @type {RedisHealth}
     * @memberof Components
     */
    'redis': RedisHealth;
    /**
     * 
     * @type {SystemHealth}
     * @memberof Components
     */
    'system': SystemHealth;
}

