/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ContractSourceOneOf } from './contract-source-one-of';
// May contain unused imports in some cases
// @ts-ignore
import type { ContractSourceOneOf1 } from './contract-source-one-of1';

/**
 * @type ContractSource
 * Represents the source for contract creation
 * @export
 */
export type ContractSource = ContractSourceOneOf | ContractSourceOneOf1;


