/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RelayerSolanaPolicy } from './relayer-solana-policy';

/**
 * 
 * @export
 * @interface CreateRelayerPolicyRequestOneOf1
 */
export interface CreateRelayerPolicyRequestOneOf1 {
    /**
     * 
     * @type {RelayerSolanaPolicy}
     * @memberof CreateRelayerPolicyRequestOneOf1
     */
    'Solana': RelayerSolanaPolicy;
}

