/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateRelayerPolicyRequestOneOf } from './create-relayer-policy-request-one-of';
// May contain unused imports in some cases
// @ts-ignore
import type { CreateRelayerPolicyRequestOneOf1 } from './create-relayer-policy-request-one-of1';
// May contain unused imports in some cases
// @ts-ignore
import type { CreateRelayerPolicyRequestOneOf2 } from './create-relayer-policy-request-one-of2';
// May contain unused imports in some cases
// @ts-ignore
import type { RelayerEvmPolicy } from './relayer-evm-policy';
// May contain unused imports in some cases
// @ts-ignore
import type { RelayerSolanaPolicy } from './relayer-solana-policy';
// May contain unused imports in some cases
// @ts-ignore
import type { RelayerStellarPolicy } from './relayer-stellar-policy';

/**
 * @type CreateRelayerPolicyRequest
 * Policy types for create requests - deserialized based on network_type from parent request
 * @export
 */
export type CreateRelayerPolicyRequest = CreateRelayerPolicyRequestOneOf | CreateRelayerPolicyRequestOneOf1 | CreateRelayerPolicyRequestOneOf2;


