/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RelayerStellarPolicy } from './relayer-stellar-policy';

/**
 * 
 * @export
 * @interface CreateRelayerPolicyRequestOneOf2
 */
export interface CreateRelayerPolicyRequestOneOf2 {
    /**
     * 
     * @type {RelayerStellarPolicy}
     * @memberof CreateRelayerPolicyRequestOneOf2
     */
    'Stellar': RelayerStellarPolicy;
}

