/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RelayerEvmPolicy } from './relayer-evm-policy';
// May contain unused imports in some cases
// @ts-ignore
import type { RelayerSolanaPolicy } from './relayer-solana-policy';
// May contain unused imports in some cases
// @ts-ignore
import type { RelayerStellarPolicy } from './relayer-stellar-policy';
// May contain unused imports in some cases
// @ts-ignore
import type { RelayerStellarSwapConfig } from './relayer-stellar-swap-config';
// May contain unused imports in some cases
// @ts-ignore
import type { StellarAllowedTokensPolicy } from './stellar-allowed-tokens-policy';
// May contain unused imports in some cases
// @ts-ignore
import type { StellarFeePaymentStrategy } from './stellar-fee-payment-strategy';

/**
 * @type CreateRelayerPolicyRequest
 * Policy types for create requests - deserialized based on network_type from parent request
 * @export
 */
export type CreateRelayerPolicyRequest = RelayerEvmPolicy | RelayerSolanaPolicy | RelayerStellarPolicy;


