/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Nonce synchronization failed during initialization
 * @export
 * @interface DisabledReasonOneOf
 */
export interface DisabledReasonOneOf {
    /**
     * Nonce synchronization failed during initialization
     * @type {string}
     * @memberof DisabledReasonOneOf
     */
    'details': string;
    /**
     * 
     * @type {string}
     * @memberof DisabledReasonOneOf
     */
    'type': DisabledReasonOneOfTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum DisabledReasonOneOfTypeEnum {
    NONCE_SYNC_FAILED = 'NonceSyncFailed'
}


