/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Multiple failures occurred simultaneously
 * @export
 * @interface DisabledReasonOneOf4
 */
export interface DisabledReasonOneOf4 {
    /**
     * Multiple failures occurred simultaneously
     * @type {Array<string>}
     * @memberof DisabledReasonOneOf4
     */
    'details': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof DisabledReasonOneOf4
     */
    'type': DisabledReasonOneOf4TypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum DisabledReasonOneOf4TypeEnum {
    MULTIPLE = 'Multiple'
}


