/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * EVM policy response model for OpenAPI documentation
 * @export
 * @interface EvmPolicyResponse
 */
export interface EvmPolicyResponse {
    [key: string]: any;

    /**
     * 
     * @type {boolean}
     * @memberof EvmPolicyResponse
     */
    'eip1559_pricing'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EvmPolicyResponse
     */
    'gas_limit_estimation'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof EvmPolicyResponse
     */
    'gas_price_cap'?: number;
    /**
     * 
     * @type {number}
     * @memberof EvmPolicyResponse
     */
    'min_balance'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof EvmPolicyResponse
     */
    'private_transactions'?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof EvmPolicyResponse
     */
    'whitelist_receivers'?: Array<string>;
}

