/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * The OpenZeppelin Relayer API provides endpoints for managing, monitoring, and interacting with relayers. It enables developers to relay and manage blockchain transactions across EVM and non-EVM networks, making it ideal for dApps and backend services that require secure and scalable transaction infrastructure.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Speed } from './speed';

/**
 * 
 * @export
 * @interface EvmTransactionRequest
 */
export interface EvmTransactionRequest {
    /**
     * 
     * @type {string}
     * @memberof EvmTransactionRequest
     */
    'data'?: string;
    /**
     * 
     * @type {number}
     * @memberof EvmTransactionRequest
     */
    'gas_limit': number;
    /**
     * 
     * @type {number}
     * @memberof EvmTransactionRequest
     */
    'gas_price'?: number;
    /**
     * 
     * @type {number}
     * @memberof EvmTransactionRequest
     */
    'max_fee_per_gas'?: number;
    /**
     * 
     * @type {number}
     * @memberof EvmTransactionRequest
     */
    'max_priority_fee_per_gas'?: number;
    /**
     * 
     * @type {Speed}
     * @memberof EvmTransactionRequest
     */
    'speed'?: Speed;
    /**
     * 
     * @type {string}
     * @memberof EvmTransactionRequest
     */
    'to'?: string;
    /**
     * 
     * @type {string}
     * @memberof EvmTransactionRequest
     */
    'valid_until'?: string;
    /**
     * 
     * @type {number}
     * @memberof EvmTransactionRequest
     */
    'value': number;
}



