/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EvmRpcRequestOneOf1
 */
export interface EvmRpcRequestOneOf1 {
    /**
     * 
     * @type {string}
     * @memberof EvmRpcRequestOneOf1
     */
    'method': string;
    /**
     * 
     * @type {any}
     * @memberof EvmRpcRequestOneOf1
     */
    'params': any;
}

