/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Unified raw request variant where params may be a JSON string or structured JSON value.
 * @export
 * @interface EvmRpcRequestOneOf
 */
export interface EvmRpcRequestOneOf {
    /**
     * 
     * @type {string}
     * @memberof EvmRpcRequestOneOf
     */
    'method': string;
    /**
     * 
     * @type {any}
     * @memberof EvmRpcRequestOneOf
     */
    'params': any;
}

