/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EvmTransactionDataSignature } from './evm-transaction-data-signature';
// May contain unused imports in some cases
// @ts-ignore
import type { Speed } from './speed';
// May contain unused imports in some cases
// @ts-ignore
import type { TransactionStatus } from './transaction-status';

/**
 * 
 * @export
 * @interface EvmTransactionResponse
 */
export interface EvmTransactionResponse {
    /**
     * 
     * @type {string}
     * @memberof EvmTransactionResponse
     */
    'confirmed_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof EvmTransactionResponse
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof EvmTransactionResponse
     */
    'data'?: string;
    /**
     * 
     * @type {string}
     * @memberof EvmTransactionResponse
     */
    'from': string;
    /**
     * 
     * @type {number}
     * @memberof EvmTransactionResponse
     */
    'gas_limit'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof EvmTransactionResponse
     */
    'gas_price'?: string;
    /**
     * 
     * @type {string}
     * @memberof EvmTransactionResponse
     */
    'hash'?: string;
    /**
     * 
     * @type {string}
     * @memberof EvmTransactionResponse
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof EvmTransactionResponse
     */
    'max_fee_per_gas'?: string;
    /**
     * 
     * @type {string}
     * @memberof EvmTransactionResponse
     */
    'max_priority_fee_per_gas'?: string;
    /**
     * 
     * @type {number}
     * @memberof EvmTransactionResponse
     */
    'nonce'?: number;
    /**
     * 
     * @type {string}
     * @memberof EvmTransactionResponse
     */
    'relayer_id': string;
    /**
     * 
     * @type {string}
     * @memberof EvmTransactionResponse
     */
    'sent_at'?: string;
    /**
     * 
     * @type {EvmTransactionDataSignature}
     * @memberof EvmTransactionResponse
     */
    'signature'?: EvmTransactionDataSignature | null;
    /**
     * 
     * @type {Speed}
     * @memberof EvmTransactionResponse
     */
    'speed'?: Speed | null;
    /**
     * 
     * @type {TransactionStatus}
     * @memberof EvmTransactionResponse
     */
    'status': TransactionStatus;
    /**
     * 
     * @type {string}
     * @memberof EvmTransactionResponse
     */
    'status_reason'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EvmTransactionResponse
     */
    'to'?: string;
    /**
     * 
     * @type {string}
     * @memberof EvmTransactionResponse
     */
    'value': string;
}



