/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EvmRpcRequestOneOf
 */
export interface EvmRpcRequestOneOf {
    /**
     * 
     * @type {string}
     * @memberof EvmRpcRequestOneOf
     */
    'method': EvmRpcRequestOneOfMethodEnum;
    /**
     * 
     * @type {string}
     * @memberof EvmRpcRequestOneOf
     */
    'params': string;
}

/**
    * @export
    * @enum {string}
    */
export enum EvmRpcRequestOneOfMethodEnum {
    GENERIC_RPC_REQUEST = 'GenericRpcRequest'
}


