/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OperationSpec } from './operation-spec';

/**
 * 
 * @export
 * @interface FeeEstimateRequestParams
 */
export interface FeeEstimateRequestParams {
    [key: string]: any;

    /**
     * Asset identifier for fee token (e.g., \"native\" or \"USDC:GA5Z...\")
     * @type {string}
     * @memberof FeeEstimateRequestParams
     */
    'fee_token': string;
    /**
     * Operations array to build transaction from Mutually exclusive with transaction_xdr field
     * @type {Array<OperationSpec>}
     * @memberof FeeEstimateRequestParams
     */
    'operations'?: Array<OperationSpec>;
    /**
     * Pre-built transaction XDR (base64 encoded, signed or unsigned) Mutually exclusive with operations field
     * @type {string}
     * @memberof FeeEstimateRequestParams
     */
    'transaction_xdr'?: string;
}

