/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetSupportedTokensItem
 */
export interface GetSupportedTokensItem {
    /**
     * 
     * @type {number}
     * @memberof GetSupportedTokensItem
     */
    'conversion_slippage_percentage'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetSupportedTokensItem
     */
    'decimals': number;
    /**
     * 
     * @type {number}
     * @memberof GetSupportedTokensItem
     */
    'max_allowed_fee'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetSupportedTokensItem
     */
    'mint': string;
    /**
     * 
     * @type {string}
     * @memberof GetSupportedTokensItem
     */
    'symbol': string;
}

