/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GoogleCloudKmsSignerServiceAccountResponseConfig
 */
export interface GoogleCloudKmsSignerServiceAccountResponseConfig {
    /**
     * 
     * @type {string}
     * @memberof GoogleCloudKmsSignerServiceAccountResponseConfig
     */
    'auth_provider_x509_cert_url': string;
    /**
     * 
     * @type {string}
     * @memberof GoogleCloudKmsSignerServiceAccountResponseConfig
     */
    'auth_uri': string;
    /**
     * 
     * @type {string}
     * @memberof GoogleCloudKmsSignerServiceAccountResponseConfig
     */
    'client_id': string;
    /**
     * 
     * @type {string}
     * @memberof GoogleCloudKmsSignerServiceAccountResponseConfig
     */
    'client_x509_cert_url': string;
    /**
     * 
     * @type {string}
     * @memberof GoogleCloudKmsSignerServiceAccountResponseConfig
     */
    'project_id': string;
    /**
     * 
     * @type {string}
     * @memberof GoogleCloudKmsSignerServiceAccountResponseConfig
     */
    'token_uri': string;
    /**
     * 
     * @type {string}
     * @memberof GoogleCloudKmsSignerServiceAccountResponseConfig
     */
    'universe_domain': string;
}

