/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Google Cloud KMS service account configuration for API requests
 * @export
 * @interface GoogleCloudKmsSignerServiceAccountRequestConfig
 */
export interface GoogleCloudKmsSignerServiceAccountRequestConfig {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof GoogleCloudKmsSignerServiceAccountRequestConfig
     */
    'auth_provider_x509_cert_url': string;
    /**
     * 
     * @type {string}
     * @memberof GoogleCloudKmsSignerServiceAccountRequestConfig
     */
    'auth_uri': string;
    /**
     * 
     * @type {string}
     * @memberof GoogleCloudKmsSignerServiceAccountRequestConfig
     */
    'client_email': string;
    /**
     * 
     * @type {string}
     * @memberof GoogleCloudKmsSignerServiceAccountRequestConfig
     */
    'client_id': string;
    /**
     * 
     * @type {string}
     * @memberof GoogleCloudKmsSignerServiceAccountRequestConfig
     */
    'client_x509_cert_url': string;
    /**
     * 
     * @type {string}
     * @memberof GoogleCloudKmsSignerServiceAccountRequestConfig
     */
    'private_key': string;
    /**
     * 
     * @type {string}
     * @memberof GoogleCloudKmsSignerServiceAccountRequestConfig
     */
    'private_key_id': string;
    /**
     * 
     * @type {string}
     * @memberof GoogleCloudKmsSignerServiceAccountRequestConfig
     */
    'project_id': string;
    /**
     * 
     * @type {string}
     * @memberof GoogleCloudKmsSignerServiceAccountRequestConfig
     */
    'token_uri': string;
    /**
     * 
     * @type {string}
     * @memberof GoogleCloudKmsSignerServiceAccountRequestConfig
     */
    'universe_domain': string;
}

