/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Google Cloud KMS key configuration for API requests
 * @export
 * @interface GoogleCloudKmsSignerKeyRequestConfig
 */
export interface GoogleCloudKmsSignerKeyRequestConfig {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof GoogleCloudKmsSignerKeyRequestConfig
     */
    'key_id': string;
    /**
     * 
     * @type {string}
     * @memberof GoogleCloudKmsSignerKeyRequestConfig
     */
    'key_ring_id': string;
    /**
     * 
     * @type {number}
     * @memberof GoogleCloudKmsSignerKeyRequestConfig
     */
    'key_version': number;
    /**
     * 
     * @type {string}
     * @memberof GoogleCloudKmsSignerKeyRequestConfig
     */
    'location': string;
}

