/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GoogleCloudKmsSignerKeyResponseConfig
 */
export interface GoogleCloudKmsSignerKeyResponseConfig {
    /**
     * 
     * @type {string}
     * @memberof GoogleCloudKmsSignerKeyResponseConfig
     */
    'key_id': string;
    /**
     * 
     * @type {string}
     * @memberof GoogleCloudKmsSignerKeyResponseConfig
     */
    'key_ring_id': string;
    /**
     * 
     * @type {number}
     * @memberof GoogleCloudKmsSignerKeyResponseConfig
     */
    'key_version': number;
    /**
     * 
     * @type {string}
     * @memberof GoogleCloudKmsSignerKeyResponseConfig
     */
    'location': string;
}

