/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GoogleCloudKmsSignerKeyRequestConfig } from './google-cloud-kms-signer-key-request-config';
// May contain unused imports in some cases
// @ts-ignore
import type { GoogleCloudKmsSignerServiceAccountRequestConfig } from './google-cloud-kms-signer-service-account-request-config';

/**
 * Google Cloud KMS signer configuration for API requests
 * @export
 * @interface GoogleCloudKmsSignerRequestConfig
 */
export interface GoogleCloudKmsSignerRequestConfig {
    /**
     * 
     * @type {GoogleCloudKmsSignerKeyRequestConfig}
     * @memberof GoogleCloudKmsSignerRequestConfig
     */
    'key': GoogleCloudKmsSignerKeyRequestConfig;
    /**
     * 
     * @type {GoogleCloudKmsSignerServiceAccountRequestConfig}
     * @memberof GoogleCloudKmsSignerRequestConfig
     */
    'service_account': GoogleCloudKmsSignerServiceAccountRequestConfig;
}

