/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface JupiterSwapOptions
 */
export interface JupiterSwapOptions {
    /**
     * 
     * @type {boolean}
     * @memberof JupiterSwapOptions
     */
    'dynamic_compute_unit_limit'?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof JupiterSwapOptions
     */
    'priority_fee_max_lamports'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof JupiterSwapOptions
     */
    'priority_level'?: string | null;
}

