/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MemoSpecOneOf } from './memo-spec-one-of';
// May contain unused imports in some cases
// @ts-ignore
import type { MemoSpecOneOf1 } from './memo-spec-one-of1';
// May contain unused imports in some cases
// @ts-ignore
import type { MemoSpecOneOf2 } from './memo-spec-one-of2';
// May contain unused imports in some cases
// @ts-ignore
import type { MemoSpecOneOf3 } from './memo-spec-one-of3';
// May contain unused imports in some cases
// @ts-ignore
import type { MemoSpecOneOf4 } from './memo-spec-one-of4';

/**
 * @type MemoSpec
 * @export
 */
export type MemoSpec = MemoSpecOneOf | MemoSpecOneOf1 | MemoSpecOneOf2 | MemoSpecOneOf3 | MemoSpecOneOf4;


