/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MemoSpecOneOf4
 */
export interface MemoSpecOneOf4 {
    /**
     * 
     * @type {string}
     * @memberof MemoSpecOneOf4
     */
    'type': MemoSpecOneOf4TypeEnum;
    /**
     * 
     * @type {Array<number>}
     * @memberof MemoSpecOneOf4
     */
    'value': Array<number>;
}

/**
    * @export
    * @enum {string}
    */
export enum MemoSpecOneOf4TypeEnum {
    RETURN = 'return'
}


