/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MemoSpecOneOf3
 */
export interface MemoSpecOneOf3 {
    /**
     * 
     * @type {string}
     * @memberof MemoSpecOneOf3
     */
    'type': MemoSpecOneOf3TypeEnum;
    /**
     * 
     * @type {Array<number>}
     * @memberof MemoSpecOneOf3
     */
    'value': Array<number>;
}

/**
    * @export
    * @enum {string}
    */
export enum MemoSpecOneOf3TypeEnum {
    HASH = 'hash'
}


