/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MemoSpecOneOf2
 */
export interface MemoSpecOneOf2 {
    /**
     * 
     * @type {string}
     * @memberof MemoSpecOneOf2
     */
    'type': MemoSpecOneOf2TypeEnum;
    /**
     * 
     * @type {number}
     * @memberof MemoSpecOneOf2
     */
    'value': number;
}

/**
    * @export
    * @enum {string}
    */
export enum MemoSpecOneOf2TypeEnum {
    ID = 'id'
}


