/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MemoSpecOneOf1
 */
export interface MemoSpecOneOf1 {
    /**
     * 
     * @type {string}
     * @memberof MemoSpecOneOf1
     */
    'type': MemoSpecOneOf1TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof MemoSpecOneOf1
     */
    'value': string;
}

/**
    * @export
    * @enum {string}
    */
export enum MemoSpecOneOf1TypeEnum {
    TEXT = 'text'
}


