/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EvmRpcRequest } from './evm-rpc-request';
// May contain unused imports in some cases
// @ts-ignore
import type { SolanaRpcRequest } from './solana-rpc-request';
// May contain unused imports in some cases
// @ts-ignore
import type { StellarRpcRequest } from './stellar-rpc-request';

/**
 * @type NetworkRpcRequest
 * @export
 */
export type NetworkRpcRequest = EvmRpcRequest | SolanaRpcRequest | StellarRpcRequest;


