/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RelayerNetworkType } from './relayer-network-type';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcConfig } from './rpc-config';

/**
 * Network response model for API endpoints.  This flattens the internal NetworkRepoModel structure for API responses, making network-type-specific fields available at the top level.
 * @export
 * @interface NetworkResponse
 */
export interface NetworkResponse {
    /**
     * Estimated average time between blocks in milliseconds
     * @type {number}
     * @memberof NetworkResponse
     */
    'average_blocktime_ms'?: number;
    /**
     * EVM-specific: Chain ID
     * @type {number}
     * @memberof NetworkResponse
     */
    'chain_id'?: number;
    /**
     * List of Explorer endpoint URLs
     * @type {Array<string>}
     * @memberof NetworkResponse
     */
    'explorer_urls'?: Array<string>;
    /**
     * EVM-specific: Network features (e.g., \"eip1559\")
     * @type {Array<string>}
     * @memberof NetworkResponse
     */
    'features'?: Array<string>;
    /**
     * Stellar-specific: Horizon URL
     * @type {string}
     * @memberof NetworkResponse
     */
    'horizon_url'?: string;
    /**
     * Unique identifier composed of network_type and name, e.g., \"evm:mainnet\"
     * @type {string}
     * @memberof NetworkResponse
     */
    'id': string;
    /**
     * Flag indicating if the network is a testnet
     * @type {boolean}
     * @memberof NetworkResponse
     */
    'is_testnet'?: boolean;
    /**
     * Name of the network (e.g., \"mainnet\", \"sepolia\")
     * @type {string}
     * @memberof NetworkResponse
     */
    'name': string;
    /**
     * Type of the network (EVM, Solana, Stellar)
     * @type {RelayerNetworkType}
     * @memberof NetworkResponse
     */
    'network_type': RelayerNetworkType;
    /**
     * Stellar-specific: Network passphrase
     * @type {string}
     * @memberof NetworkResponse
     */
    'passphrase'?: string;
    /**
     * EVM-specific: Required confirmations
     * @type {number}
     * @memberof NetworkResponse
     */
    'required_confirmations'?: number;
    /**
     * List of RPC endpoint configurations
     * @type {Array<RpcConfig>}
     * @memberof NetworkResponse
     */
    'rpc_urls'?: Array<RpcConfig>;
    /**
     * EVM-specific: Native token symbol
     * @type {string}
     * @memberof NetworkResponse
     */
    'symbol'?: string;
    /**
     * List of arbitrary tags for categorizing or filtering networks
     * @type {Array<string>}
     * @memberof NetworkResponse
     */
    'tags'?: Array<string>;
}



