/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EvmTransactionRequest } from './evm-transaction-request';
// May contain unused imports in some cases
// @ts-ignore
import type { MemoSpec } from './memo-spec';
// May contain unused imports in some cases
// @ts-ignore
import type { OperationSpec } from './operation-spec';
// May contain unused imports in some cases
// @ts-ignore
import type { SolanaInstructionSpec } from './solana-instruction-spec';
// May contain unused imports in some cases
// @ts-ignore
import type { SolanaTransactionRequest } from './solana-transaction-request';
// May contain unused imports in some cases
// @ts-ignore
import type { Speed } from './speed';
// May contain unused imports in some cases
// @ts-ignore
import type { StellarTransactionRequest } from './stellar-transaction-request';

/**
 * @type NetworkTransactionRequest
 * @export
 */
export type NetworkTransactionRequest = EvmTransactionRequest | SolanaTransactionRequest | StellarTransactionRequest;


