/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * The OpenZeppelin Relayer API provides endpoints for managing, monitoring, and interacting with relayers. It enables developers to relay and manage blockchain transactions across EVM and non-EVM networks, making it ideal for dApps and backend services that require secure and scalable transaction infrastructure.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EvmTransactionRequest } from './evm-transaction-request';
// May contain unused imports in some cases
// @ts-ignore
import type { MemoSpec } from './memo-spec';
// May contain unused imports in some cases
// @ts-ignore
import type { OperationSpec } from './operation-spec';
// May contain unused imports in some cases
// @ts-ignore
import type { SolanaTransactionRequest } from './solana-transaction-request';
// May contain unused imports in some cases
// @ts-ignore
import type { Speed } from './speed';
// May contain unused imports in some cases
// @ts-ignore
import type { StellarTransactionRequest } from './stellar-transaction-request';

/**
 * @type NetworkTransactionRequest
 * @export
 */
export type NetworkTransactionRequest = EvmTransactionRequest | SolanaTransactionRequest | StellarTransactionRequest;


