/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { NotificationType } from './notification-type';

/**
 * Request structure for updating an existing notification
 * @export
 * @interface NotificationUpdateRequest
 */
export interface NotificationUpdateRequest {
    [key: string]: any;

    /**
     * Optional signing key for securing webhook notifications. - None: don\'t change the existing signing key - Some(\"\"): remove the signing key - Some(\"key\"): set the signing key to the provided value
     * @type {string}
     * @memberof NotificationUpdateRequest
     */
    'signing_key'?: string;
    /**
     * 
     * @type {NotificationType}
     * @memberof NotificationUpdateRequest
     */
    'type'?: NotificationType;
    /**
     * 
     * @type {string}
     * @memberof NotificationUpdateRequest
     */
    'url'?: string;
}



