/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { NotificationType } from './notification-type';

/**
 * Request structure for creating a new notification
 * @export
 * @interface NotificationCreateRequest
 */
export interface NotificationCreateRequest {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof NotificationCreateRequest
     */
    'id'?: string;
    /**
     * Optional signing key for securing webhook notifications
     * @type {string}
     * @memberof NotificationCreateRequest
     */
    'signing_key'?: string;
    /**
     * 
     * @type {NotificationType}
     * @memberof NotificationCreateRequest
     */
    'type'?: NotificationType;
    /**
     * 
     * @type {string}
     * @memberof NotificationCreateRequest
     */
    'url': string;
}



