/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AssetSpec } from './asset-spec';
// May contain unused imports in some cases
// @ts-ignore
import type { AuthSpec } from './auth-spec';
// May contain unused imports in some cases
// @ts-ignore
import type { ContractSource } from './contract-source';
// May contain unused imports in some cases
// @ts-ignore
import type { OperationSpecOneOf } from './operation-spec-one-of';
// May contain unused imports in some cases
// @ts-ignore
import type { OperationSpecOneOf1 } from './operation-spec-one-of1';
// May contain unused imports in some cases
// @ts-ignore
import type { OperationSpecOneOf2 } from './operation-spec-one-of2';
// May contain unused imports in some cases
// @ts-ignore
import type { OperationSpecOneOf3 } from './operation-spec-one-of3';
// May contain unused imports in some cases
// @ts-ignore
import type { WasmSource } from './wasm-source';

/**
 * @type OperationSpec
 * @export
 */
export type OperationSpec = OperationSpecOneOf | OperationSpecOneOf1 | OperationSpecOneOf2 | OperationSpecOneOf3;


