/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthSpec } from './auth-spec';
// May contain unused imports in some cases
// @ts-ignore
import type { ContractSource } from './contract-source';

/**
 * 
 * @export
 * @interface OperationSpecOneOf2
 */
export interface OperationSpecOneOf2 {
    /**
     * 
     * @type {AuthSpec}
     * @memberof OperationSpecOneOf2
     */
    'auth'?: AuthSpec | null;
    /**
     * 
     * @type {Array<any>}
     * @memberof OperationSpecOneOf2
     */
    'constructor_args'?: Array<any> | null;
    /**
     * 
     * @type {string}
     * @memberof OperationSpecOneOf2
     */
    'salt'?: string | null;
    /**
     * 
     * @type {ContractSource}
     * @memberof OperationSpecOneOf2
     */
    'source': ContractSource;
    /**
     * 
     * @type {string}
     * @memberof OperationSpecOneOf2
     */
    'type': OperationSpecOneOf2TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof OperationSpecOneOf2
     */
    'wasm_hash': string;
}

/**
    * @export
    * @enum {string}
    */
export enum OperationSpecOneOf2TypeEnum {
    CREATE_CONTRACT = 'create_contract'
}


