/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AssetSpec } from './asset-spec';

/**
 * 
 * @export
 * @interface OperationSpecOneOf
 */
export interface OperationSpecOneOf {
    /**
     * 
     * @type {number}
     * @memberof OperationSpecOneOf
     */
    'amount': number;
    /**
     * 
     * @type {AssetSpec}
     * @memberof OperationSpecOneOf
     */
    'asset': AssetSpec;
    /**
     * 
     * @type {string}
     * @memberof OperationSpecOneOf
     */
    'destination': string;
    /**
     * 
     * @type {string}
     * @memberof OperationSpecOneOf
     */
    'op': OperationSpecOneOfOpEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum OperationSpecOneOfOpEnum {
    PAYMENT = 'payment'
}


