/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthSpec } from './auth-spec';
// May contain unused imports in some cases
// @ts-ignore
import type { WasmSource } from './wasm-source';

/**
 * 
 * @export
 * @interface OperationSpecOneOf3
 */
export interface OperationSpecOneOf3 {
    /**
     * 
     * @type {AuthSpec}
     * @memberof OperationSpecOneOf3
     */
    'auth'?: AuthSpec | null;
    /**
     * 
     * @type {string}
     * @memberof OperationSpecOneOf3
     */
    'type': OperationSpecOneOf3TypeEnum;
    /**
     * 
     * @type {WasmSource}
     * @memberof OperationSpecOneOf3
     */
    'wasm': WasmSource;
}

/**
    * @export
    * @enum {string}
    */
export enum OperationSpecOneOf3TypeEnum {
    UPLOAD_WASM = 'upload_wasm'
}


