/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LogEntry } from './log-entry';

/**
 * 
 * @export
 * @interface PluginMetadata
 */
export interface PluginMetadata {
    /**
     * 
     * @type {Array<LogEntry>}
     * @memberof PluginMetadata
     */
    'logs'?: Array<LogEntry> | null;
    /**
     * 
     * @type {Array<any>}
     * @memberof PluginMetadata
     */
    'traces'?: Array<any> | null;
}

