/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ComponentStatus } from './component-status';

/**
 * Plugin health information.
 * @export
 * @interface PluginHealth
 */
export interface PluginHealth {
    /**
     * Average response time in milliseconds
     * @type {number}
     * @memberof PluginHealth
     */
    'avg_response_time_ms'?: number;
    /**
     * 
     * @type {string}
     * @memberof PluginHealth
     */
    'circuit_state'?: string;
    /**
     * Connection pool active connections (for pool server connections)
     * @type {number}
     * @memberof PluginHealth
     */
    'connection_pool_active_connections'?: number;
    /**
     * Connection pool available slots (for pool server connections)
     * @type {number}
     * @memberof PluginHealth
     */
    'connection_pool_available_slots'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PluginHealth
     */
    'enabled': boolean;
    /**
     * 
     * @type {string}
     * @memberof PluginHealth
     */
    'error'?: string;
    /**
     * Memory usage in bytes
     * @type {number}
     * @memberof PluginHealth
     */
    'memory'?: number;
    /**
     * Number of completed tasks in the pool
     * @type {number}
     * @memberof PluginHealth
     */
    'pool_completed'?: number;
    /**
     * Number of queued tasks in the pool
     * @type {number}
     * @memberof PluginHealth
     */
    'pool_queued'?: number;
    /**
     * Whether recovery mode is active
     * @type {boolean}
     * @memberof PluginHealth
     */
    'recovering'?: boolean;
    /**
     * Current recovery allowance percentage
     * @type {number}
     * @memberof PluginHealth
     */
    'recovery_percent'?: number;
    /**
     * Shared socket active connection count
     * @type {number}
     * @memberof PluginHealth
     */
    'shared_socket_active_connections'?: number;
    /**
     * Shared socket available connection slots
     * @type {number}
     * @memberof PluginHealth
     */
    'shared_socket_available_slots'?: number;
    /**
     * Shared socket registered execution count
     * @type {number}
     * @memberof PluginHealth
     */
    'shared_socket_registered_executions'?: number;
    /**
     * 
     * @type {ComponentStatus}
     * @memberof PluginHealth
     */
    'status': ComponentStatus;
    /**
     * Success rate as a percentage (0.0-100.0)
     * @type {number}
     * @memberof PluginHealth
     */
    'success_rate'?: number;
    /**
     * Plugin uptime in milliseconds
     * @type {number}
     * @memberof PluginHealth
     */
    'uptime_ms'?: number;
}



