/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LogEntry } from './log-entry';

/**
 * 
 * @export
 * @interface PluginCallResponse
 */
export interface PluginCallResponse {
    /**
     * 
     * @type {string}
     * @memberof PluginCallResponse
     */
    'error': string;
    /**
     * 
     * @type {Array<LogEntry>}
     * @memberof PluginCallResponse
     */
    'logs': Array<LogEntry>;
    /**
     * 
     * @type {string}
     * @memberof PluginCallResponse
     */
    'message': string;
    /**
     * 
     * @type {string}
     * @memberof PluginCallResponse
     */
    'return_value': string;
    /**
     * 
     * @type {boolean}
     * @memberof PluginCallResponse
     */
    'success': boolean;
    /**
     * 
     * @type {Array<any>}
     * @memberof PluginCallResponse
     */
    'traces': Array<any>;
}

