/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Status of an individual Redis connection pool.
 * @export
 * @interface PoolStatus
 */
export interface PoolStatus {
    /**
     * Number of available connections in the pool.
     * @type {number}
     * @memberof PoolStatus
     */
    'available': number;
    /**
     * Whether the pool is connected and responding to PING.
     * @type {boolean}
     * @memberof PoolStatus
     */
    'connected': boolean;
    /**
     * Error message if the pool is not healthy.
     * @type {string}
     * @memberof PoolStatus
     */
    'error'?: string;
    /**
     * Maximum configured pool size.
     * @type {number}
     * @memberof PoolStatus
     */
    'max_size': number;
}

