/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PrepareTransactionRequestParams
 */
export interface PrepareTransactionRequestParams {
    /**
     * 
     * @type {string}
     * @memberof PrepareTransactionRequestParams
     */
    'fee_token': string;
    /**
     * 
     * @type {string}
     * @memberof PrepareTransactionRequestParams
     */
    'transaction': string;
}

