/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ComponentStatus } from './component-status';

/**
 * Queue health information.
 * @export
 * @interface QueueHealth
 */
export interface QueueHealth {
    /**
     * 
     * @type {string}
     * @memberof QueueHealth
     */
    'error'?: string;
    /**
     * 
     * @type {ComponentStatus}
     * @memberof QueueHealth
     */
    'status': ComponentStatus;
}



