/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ComponentStatus } from './component-status';
// May contain unused imports in some cases
// @ts-ignore
import type { PoolStatus } from './pool-status';

/**
 * Redis health information.
 * @export
 * @interface RedisHealth
 */
export interface RedisHealth {
    /**
     * 
     * @type {string}
     * @memberof RedisHealth
     */
    'error'?: string;
    /**
     * 
     * @type {PoolStatus}
     * @memberof RedisHealth
     */
    'primary_pool': PoolStatus;
    /**
     * 
     * @type {PoolStatus}
     * @memberof RedisHealth
     */
    'reader_pool': PoolStatus;
    /**
     * 
     * @type {ComponentStatus}
     * @memberof RedisHealth
     */
    'status': ComponentStatus;
}



