/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StellarSwapStrategy } from './stellar-swap-strategy';

/**
 * Stellar swap policy configuration
 * @export
 * @interface RelayerStellarSwapConfig
 */
export interface RelayerStellarSwapConfig {
    [key: string]: any;

    /**
     * Cron schedule for executing token swap logic to keep relayer funded. Optional.
     * @type {string}
     * @memberof RelayerStellarSwapConfig
     */
    'cron_schedule'?: string;
    /**
     * Min XLM balance (in stroops) to execute token swap logic to keep relayer funded. Optional.
     * @type {number}
     * @memberof RelayerStellarSwapConfig
     */
    'min_balance_threshold'?: number;
    /**
     * DEX strategies to use for token swaps, in priority order. Strategies are tried sequentially until one can handle the asset.
     * @type {Array<StellarSwapStrategy>}
     * @memberof RelayerStellarSwapConfig
     */
    'strategies'?: Array<StellarSwapStrategy>;
}

