/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RelayerSolanaSwapConfigJupiterSwapOptions } from './relayer-solana-swap-config-jupiter-swap-options';
// May contain unused imports in some cases
// @ts-ignore
import type { RelayerSolanaSwapConfigStrategy } from './relayer-solana-swap-config-strategy';

/**
 * 
 * @export
 * @interface RelayerSolanaSwapConfig
 */
export interface RelayerSolanaSwapConfig {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof RelayerSolanaSwapConfig
     */
    'cron_schedule'?: string;
    /**
     * 
     * @type {RelayerSolanaSwapConfigJupiterSwapOptions}
     * @memberof RelayerSolanaSwapConfig
     */
    'jupiter_swap_options'?: RelayerSolanaSwapConfigJupiterSwapOptions;
    /**
     * 
     * @type {number}
     * @memberof RelayerSolanaSwapConfig
     */
    'min_balance_threshold'?: number;
    /**
     * 
     * @type {RelayerSolanaSwapConfigStrategy}
     * @memberof RelayerSolanaSwapConfig
     */
    'strategy'?: RelayerSolanaSwapConfigStrategy;
}

