/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EvmPolicyResponse } from './evm-policy-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RelayerSolanaSwapConfig } from './relayer-solana-swap-config';
// May contain unused imports in some cases
// @ts-ignore
import type { SolanaAllowedTokensPolicy } from './solana-allowed-tokens-policy';
// May contain unused imports in some cases
// @ts-ignore
import type { SolanaFeePaymentStrategy } from './solana-fee-payment-strategy';
// May contain unused imports in some cases
// @ts-ignore
import type { SolanaPolicyResponse } from './solana-policy-response';
// May contain unused imports in some cases
// @ts-ignore
import type { StellarPolicyResponse } from './stellar-policy-response';

/**
 * @type RelayerNetworkPolicyResponse
 * Policy types for responses - these don\'t include network_type tags since the network_type is already available at the top level of RelayerResponse
 * @export
 */
export type RelayerNetworkPolicyResponse = EvmPolicyResponse | SolanaPolicyResponse | StellarPolicyResponse;


