/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RelayerNetworkPolicyOneOf } from './relayer-network-policy-one-of';
// May contain unused imports in some cases
// @ts-ignore
import type { RelayerNetworkPolicyOneOf1 } from './relayer-network-policy-one-of1';
// May contain unused imports in some cases
// @ts-ignore
import type { RelayerNetworkPolicyOneOf2 } from './relayer-network-policy-one-of2';
// May contain unused imports in some cases
// @ts-ignore
import type { RelayerStellarSwapConfig } from './relayer-stellar-swap-config';
// May contain unused imports in some cases
// @ts-ignore
import type { StellarAllowedTokensPolicy } from './stellar-allowed-tokens-policy';
// May contain unused imports in some cases
// @ts-ignore
import type { StellarFeePaymentStrategy } from './stellar-fee-payment-strategy';

/**
 * @type RelayerNetworkPolicy
 * Network-specific policy for relayers
 * @export
 */
export type RelayerNetworkPolicy = RelayerNetworkPolicyOneOf | RelayerNetworkPolicyOneOf1 | RelayerNetworkPolicyOneOf2;


