/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RelayerStellarSwapConfig } from './relayer-stellar-swap-config';
// May contain unused imports in some cases
// @ts-ignore
import type { StellarAllowedTokensPolicy } from './stellar-allowed-tokens-policy';
// May contain unused imports in some cases
// @ts-ignore
import type { StellarFeePaymentStrategy } from './stellar-fee-payment-strategy';

/**
 * Stellar-specific relayer policy configuration
 * @export
 * @interface RelayerStellarPolicy
 */
export interface RelayerStellarPolicy {
    [key: string]: any;

    /**
     * 
     * @type {Array<StellarAllowedTokensPolicy>}
     * @memberof RelayerStellarPolicy
     */
    'allowed_tokens'?: Array<StellarAllowedTokensPolicy>;
    /**
     * 
     * @type {boolean}
     * @memberof RelayerStellarPolicy
     */
    'concurrent_transactions'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof RelayerStellarPolicy
     */
    'fee_margin_percentage'?: number;
    /**
     * Fee payment strategy - determines who pays transaction fees (optional)
     * @type {StellarFeePaymentStrategy}
     * @memberof RelayerStellarPolicy
     */
    'fee_payment_strategy'?: StellarFeePaymentStrategy;
    /**
     * 
     * @type {number}
     * @memberof RelayerStellarPolicy
     */
    'max_fee'?: number;
    /**
     * 
     * @type {number}
     * @memberof RelayerStellarPolicy
     */
    'min_balance'?: number;
    /**
     * 
     * @type {number}
     * @memberof RelayerStellarPolicy
     */
    'slippage_percentage'?: number;
    /**
     * 
     * @type {RelayerStellarSwapConfig}
     * @memberof RelayerStellarPolicy
     */
    'swap_config'?: RelayerStellarSwapConfig;
    /**
     * 
     * @type {number}
     * @memberof RelayerStellarPolicy
     */
    'timeout_seconds'?: number;
}



