/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * The OpenZeppelin Relayer API provides endpoints for managing, monitoring, and interacting with relayers. It enables developers to relay and manage blockchain transactions across EVM and non-EVM networks, making it ideal for dApps and backend services that require secure and scalable transaction infrastructure.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { JupiterSwapOptions } from './jupiter-swap-options';
// May contain unused imports in some cases
// @ts-ignore
import type { SolanaSwapStrategy } from './solana-swap-strategy';

/**
 * 
 * @export
 * @interface RelayerSolanaSwapConfig
 */
export interface RelayerSolanaSwapConfig {
    /**
     * 
     * @type {string}
     * @memberof RelayerSolanaSwapConfig
     */
    'cron_schedule'?: string | null;
    /**
     * 
     * @type {JupiterSwapOptions}
     * @memberof RelayerSolanaSwapConfig
     */
    'jupiter_swap_options'?: JupiterSwapOptions | null;
    /**
     * 
     * @type {number}
     * @memberof RelayerSolanaSwapConfig
     */
    'min_balance_threshold'?: number | null;
    /**
     * 
     * @type {SolanaSwapStrategy}
     * @memberof RelayerSolanaSwapConfig
     */
    'strategy'?: SolanaSwapStrategy | null;
}



