/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Stellar-specific relayer policy configuration
 * @export
 * @interface RelayerStellarPolicy
 */
export interface RelayerStellarPolicy {
    /**
     * 
     * @type {number}
     * @memberof RelayerStellarPolicy
     */
    'max_fee'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof RelayerStellarPolicy
     */
    'min_balance'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof RelayerStellarPolicy
     */
    'timeout_seconds'?: number | null;
}

