/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * EVM-specific relayer policy configuration
 * @export
 * @interface RelayerEvmPolicy
 */
export interface RelayerEvmPolicy {
    /**
     * 
     * @type {boolean}
     * @memberof RelayerEvmPolicy
     */
    'eip1559_pricing'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof RelayerEvmPolicy
     */
    'gas_limit_estimation'?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof RelayerEvmPolicy
     */
    'gas_price_cap'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof RelayerEvmPolicy
     */
    'min_balance'?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof RelayerEvmPolicy
     */
    'private_transactions'?: boolean | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof RelayerEvmPolicy
     */
    'whitelist_receivers'?: Array<string> | null;
}

