/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Configuration for an RPC endpoint.
 * @export
 * @interface RpcConfig
 */
export interface RpcConfig {
    /**
     * The RPC endpoint URL.
     * @type {string}
     * @memberof RpcConfig
     */
    'url': string;
    /**
     * The weight of this endpoint in the weighted round-robin selection. Defaults to DEFAULT_RPC_WEIGHT (100). Should be between 0 and 100.
     * @type {number}
     * @memberof RpcConfig
     */
    'weight'?: number;
}

