/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RpcConfig } from './rpc-config';

/**
 * @type RpcUrlEntry
 * Schema-only type representing a flexible RPC URL entry. Used for OpenAPI documentation to show that rpc_urls can accept either strings or RpcConfig objects.  This is NOT used for actual deserialization - the custom deserializer handles the conversion. This type exists solely for schema generation.
 * @export
 */
export type RpcUrlEntry = RpcConfig | string;


