/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SignerConfigResponseOneOf4
 */
export interface SignerConfigResponseOneOf4 {
    /**
     * 
     * @type {string}
     * @memberof SignerConfigResponseOneOf4
     */
    'account_address': string;
    /**
     * 
     * @type {string}
     * @memberof SignerConfigResponseOneOf4
     */
    'api_key_id': string;
}

