/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SignTransactionRequestStellar
 */
export interface SignTransactionRequestStellar {
    /**
     * 
     * @type {string}
     * @memberof SignTransactionRequestStellar
     */
    'unsigned_xdr': string;
}

