/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiResponseSignTransactionResponseDataOneOf } from './api-response-sign-transaction-response-data-one-of';
// May contain unused imports in some cases
// @ts-ignore
import type { ApiResponseSignTransactionResponseDataOneOf1 } from './api-response-sign-transaction-response-data-one-of1';
// May contain unused imports in some cases
// @ts-ignore
import type { ApiResponseSignTransactionResponseDataOneOf2 } from './api-response-sign-transaction-response-data-one-of2';

/**
 * @type SignTransactionResponse
 * @export
 */
export type SignTransactionResponse = ApiResponseSignTransactionResponseDataOneOf | ApiResponseSignTransactionResponseDataOneOf1 | ApiResponseSignTransactionResponseDataOneOf2;


