/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Signer type enum for API requests
 * @export
 * @enum {string}
 */

export enum SignerTypeRequest {
    PLAIN = 'plain',
    AWS_KMS = 'aws_kms',
    VAULT = 'vault',
    VAULT_TRANSIT = 'vault_transit',
    TURNKEY = 'turnkey',
    GOOGLE_CLOUD_KMS = 'google_cloud_kms'
}



