/* tslint:disable */
 
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SignDataResponseEvm
 */
export interface SignDataResponseEvm {
    /**
     * 
     * @type {string}
     * @memberof SignDataResponseEvm
     */
    'r': string;
    /**
     * 
     * @type {string}
     * @memberof SignDataResponseEvm
     */
    's': string;
    /**
     * 
     * @type {string}
     * @memberof SignDataResponseEvm
     */
    'sig': string;
    /**
     * 
     * @type {number}
     * @memberof SignDataResponseEvm
     */
    'v': number;
}

