/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SignerConfigRequest } from './signer-config-request';
// May contain unused imports in some cases
// @ts-ignore
import type { SignerTypeRequest } from './signer-type-request';

/**
 * Request model for creating a new signer
 * @export
 * @interface SignerCreateRequest
 */
export interface SignerCreateRequest {
    [key: string]: any;

    /**
     * The signer configuration
     * @type {SignerConfigRequest}
     * @memberof SignerCreateRequest
     */
    'config': SignerConfigRequest;
    /**
     * Optional ID - if not provided, a UUID will be generated
     * @type {string}
     * @memberof SignerCreateRequest
     */
    'id'?: string;
    /**
     * The type of signer
     * @type {SignerTypeRequest}
     * @memberof SignerCreateRequest
     */
    'type': SignerTypeRequest;
}



