/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SignTransactionResponseStellar
 */
export interface SignTransactionResponseStellar {
    /**
     * 
     * @type {string}
     * @memberof SignTransactionResponseStellar
     */
    'signature': string;
    /**
     * 
     * @type {string}
     * @memberof SignTransactionResponseStellar
     */
    'signedXdr': string;
}

