/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SignerConfigResponseOneOf3
 */
export interface SignerConfigResponseOneOf3 {
    /**
     * 
     * @type {string}
     * @memberof SignerConfigResponseOneOf3
     */
    'api_public_key': string;
    /**
     * 
     * @type {string}
     * @memberof SignerConfigResponseOneOf3
     */
    'organization_id': string;
    /**
     * 
     * @type {string}
     * @memberof SignerConfigResponseOneOf3
     */
    'private_key_id': string;
    /**
     * 
     * @type {string}
     * @memberof SignerConfigResponseOneOf3
     */
    'public_key': string;
}

