/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Signer type enum used for validation and API responses
 * @export
 * @enum {string}
 */

export enum SignerType {
    LOCAL = 'local',
    AWS_KMS = 'aws_kms',
    GOOGLE_CLOUD_KMS = 'google_cloud_kms',
    VAULT = 'vault',
    VAULT_TRANSIT = 'vault_transit',
    TURNKEY = 'turnkey',
    CDP = 'cdp'
}



