/* tslint:disable */
 
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SignAndSendTransactionRequestParams
 */
export interface SignAndSendTransactionRequestParams {
    /**
     * 
     * @type {string}
     * @memberof SignAndSendTransactionRequestParams
     */
    'transaction': string;
}

