/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SignerConfigResponseOneOf2
 */
export interface SignerConfigResponseOneOf2 {
    /**
     * 
     * @type {string}
     * @memberof SignerConfigResponseOneOf2
     */
    'key_id': string;
    /**
     * 
     * @type {string}
     * @memberof SignerConfigResponseOneOf2
     */
    'region'?: string | null;
}

