/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GoogleCloudKmsSignerKeyResponseConfig } from './google-cloud-kms-signer-key-response-config';
// May contain unused imports in some cases
// @ts-ignore
import type { GoogleCloudKmsSignerServiceAccountResponseConfig } from './google-cloud-kms-signer-service-account-response-config';
// May contain unused imports in some cases
// @ts-ignore
import type { SignerConfigResponseOneOf } from './signer-config-response-one-of';
// May contain unused imports in some cases
// @ts-ignore
import type { SignerConfigResponseOneOf1 } from './signer-config-response-one-of1';
// May contain unused imports in some cases
// @ts-ignore
import type { SignerConfigResponseOneOf2 } from './signer-config-response-one-of2';
// May contain unused imports in some cases
// @ts-ignore
import type { SignerConfigResponseOneOf3 } from './signer-config-response-one-of3';
// May contain unused imports in some cases
// @ts-ignore
import type { SignerConfigResponseOneOf4 } from './signer-config-response-one-of4';
// May contain unused imports in some cases
// @ts-ignore
import type { SignerConfigResponseOneOf5 } from './signer-config-response-one-of5';

/**
 * @type SignerConfigResponse
 * Signer configuration response Does not include sensitive information like private keys
 * @export
 */
export type SignerConfigResponse = SignerConfigResponseOneOf | SignerConfigResponseOneOf1 | SignerConfigResponseOneOf2 | SignerConfigResponseOneOf3 | SignerConfigResponseOneOf4 | SignerConfigResponseOneOf5 | object;


