/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AwsKmsSignerRequestConfig } from './aws-kms-signer-request-config';
// May contain unused imports in some cases
// @ts-ignore
import type { CdpSignerRequestConfig } from './cdp-signer-request-config';
// May contain unused imports in some cases
// @ts-ignore
import type { GoogleCloudKmsSignerKeyRequestConfig } from './google-cloud-kms-signer-key-request-config';
// May contain unused imports in some cases
// @ts-ignore
import type { GoogleCloudKmsSignerRequestConfig } from './google-cloud-kms-signer-request-config';
// May contain unused imports in some cases
// @ts-ignore
import type { GoogleCloudKmsSignerServiceAccountRequestConfig } from './google-cloud-kms-signer-service-account-request-config';
// May contain unused imports in some cases
// @ts-ignore
import type { LocalSignerRequestConfig } from './local-signer-request-config';
// May contain unused imports in some cases
// @ts-ignore
import type { TurnkeySignerRequestConfig } from './turnkey-signer-request-config';
// May contain unused imports in some cases
// @ts-ignore
import type { VaultSignerRequestConfig } from './vault-signer-request-config';
// May contain unused imports in some cases
// @ts-ignore
import type { VaultTransitSignerRequestConfig } from './vault-transit-signer-request-config';

/**
 * @type SignerConfigRequest
 * Signer configuration enum for API requests (without type discriminator)
 * @export
 */
export type SignerConfigRequest = AwsKmsSignerRequestConfig | CdpSignerRequestConfig | GoogleCloudKmsSignerRequestConfig | LocalSignerRequestConfig | TurnkeySignerRequestConfig | VaultSignerRequestConfig | VaultTransitSignerRequestConfig;


