/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SignerConfigResponseOneOf1
 */
export interface SignerConfigResponseOneOf1 {
    /**
     * 
     * @type {string}
     * @memberof SignerConfigResponseOneOf1
     */
    'address': string;
    /**
     * 
     * @type {string}
     * @memberof SignerConfigResponseOneOf1
     */
    'key_name': string;
    /**
     * 
     * @type {string}
     * @memberof SignerConfigResponseOneOf1
     */
    'mount_point'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SignerConfigResponseOneOf1
     */
    'namespace'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SignerConfigResponseOneOf1
     */
    'pubkey': string;
}

