/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SolanaFeeEstimateRequestParams
 */
export interface SolanaFeeEstimateRequestParams {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof SolanaFeeEstimateRequestParams
     */
    'fee_token': string;
    /**
     * 
     * @type {string}
     * @memberof SolanaFeeEstimateRequestParams
     */
    'transaction': string;
}

