/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TransactionStatus } from './transaction-status';

/**
 * 
 * @export
 * @interface SolanaTransactionResponse
 */
export interface SolanaTransactionResponse {
    /**
     * 
     * @type {string}
     * @memberof SolanaTransactionResponse
     */
    'confirmed_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof SolanaTransactionResponse
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof SolanaTransactionResponse
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof SolanaTransactionResponse
     */
    'sent_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof SolanaTransactionResponse
     */
    'signature'?: string;
    /**
     * 
     * @type {TransactionStatus}
     * @memberof SolanaTransactionResponse
     */
    'status': TransactionStatus;
    /**
     * 
     * @type {string}
     * @memberof SolanaTransactionResponse
     */
    'status_reason'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SolanaTransactionResponse
     */
    'transaction': string;
}



