/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SolanaAllowedTokensPolicy } from './solana-allowed-tokens-policy';

/**
 * 
 * @export
 * @interface SolanaPolicyResponse
 */
export interface SolanaPolicyResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof SolanaPolicyResponse
     */
    'allowed_accounts'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SolanaPolicyResponse
     */
    'allowed_programs'?: Array<string>;
    /**
     * 
     * @type {Array<SolanaAllowedTokensPolicy>}
     * @memberof SolanaPolicyResponse
     */
    'allowed_tokens'?: Array<SolanaAllowedTokensPolicy>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SolanaPolicyResponse
     */
    'disallowed_accounts'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof SolanaPolicyResponse
     */
    'max_allowed_transfer_amount_lamports'?: number;
    /**
     * 
     * @type {number}
     * @memberof SolanaPolicyResponse
     */
    'max_signatures'?: number;
    /**
     * 
     * @type {number}
     * @memberof SolanaPolicyResponse
     */
    'max_tx_data_size': number;
    /**
     * 
     * @type {number}
     * @memberof SolanaPolicyResponse
     */
    'min_balance': number;
}

