/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Solana token swap configuration
 * @export
 * @interface SolanaAllowedTokensSwapConfig
 */
export interface SolanaAllowedTokensSwapConfig {
    [key: string]: any;

    /**
     * Maximum amount of tokens to swap. Optional.
     * @type {number}
     * @memberof SolanaAllowedTokensSwapConfig
     */
    'max_amount'?: number;
    /**
     * Minimum amount of tokens to swap. Optional.
     * @type {number}
     * @memberof SolanaAllowedTokensSwapConfig
     */
    'min_amount'?: number;
    /**
     * Minimum amount of tokens to retain after swap. Optional.
     * @type {number}
     * @memberof SolanaAllowedTokensSwapConfig
     */
    'retain_min_amount'?: number;
    /**
     * Conversion slippage percentage for token. Optional.
     * @type {number}
     * @memberof SolanaAllowedTokensSwapConfig
     */
    'slippage_percentage'?: number;
}

