/* tslint:disable */
 
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SolanaAllowedTokensPolicy
 */
export interface SolanaAllowedTokensPolicy {
    /**
     * 
     * @type {number}
     * @memberof SolanaAllowedTokensPolicy
     */
    'conversion_slippage_percentage'?: number;
    /**
     * 
     * @type {number}
     * @memberof SolanaAllowedTokensPolicy
     */
    'decimals'?: number;
    /**
     * 
     * @type {number}
     * @memberof SolanaAllowedTokensPolicy
     */
    'max_allowed_fee'?: number;
    /**
     * 
     * @type {string}
     * @memberof SolanaAllowedTokensPolicy
     */
    'mint': string;
    /**
     * 
     * @type {string}
     * @memberof SolanaAllowedTokensPolicy
     */
    'symbol'?: string;
}

