/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SolanaTransactionRequest
 */
export interface SolanaTransactionRequest {
    /**
     * 
     * @type {string}
     * @memberof SolanaTransactionRequest
     */
    'fee_payer': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SolanaTransactionRequest
     */
    'instructions': Array<string>;
}

