/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SolanaRpcRequestOneOf } from './solana-rpc-request-one-of';
// May contain unused imports in some cases
// @ts-ignore
import type { SolanaRpcRequestOneOf1 } from './solana-rpc-request-one-of1';
// May contain unused imports in some cases
// @ts-ignore
import type { SolanaRpcRequestOneOf2 } from './solana-rpc-request-one-of2';
// May contain unused imports in some cases
// @ts-ignore
import type { SolanaRpcRequestOneOf3 } from './solana-rpc-request-one-of3';
// May contain unused imports in some cases
// @ts-ignore
import type { SolanaRpcRequestOneOf4 } from './solana-rpc-request-one-of4';
// May contain unused imports in some cases
// @ts-ignore
import type { SolanaRpcRequestOneOf5 } from './solana-rpc-request-one-of5';
// May contain unused imports in some cases
// @ts-ignore
import type { SolanaRpcRequestOneOf6 } from './solana-rpc-request-one-of6';

/**
 * @type SolanaRpcRequest
 * @export
 */
export type SolanaRpcRequest = SolanaRpcRequestOneOf | SolanaRpcRequestOneOf1 | SolanaRpcRequestOneOf2 | SolanaRpcRequestOneOf3 | SolanaRpcRequestOneOf4 | SolanaRpcRequestOneOf5 | SolanaRpcRequestOneOf6;


