/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SignTransactionRequestParams } from './sign-transaction-request-params';

/**
 * 
 * @export
 * @interface SolanaRpcRequestOneOf3
 */
export interface SolanaRpcRequestOneOf3 {
    /**
     * 
     * @type {string}
     * @memberof SolanaRpcRequestOneOf3
     */
    'method': SolanaRpcRequestOneOf3MethodEnum;
    /**
     * 
     * @type {SignTransactionRequestParams}
     * @memberof SolanaRpcRequestOneOf3
     */
    'params': SignTransactionRequestParams;
}

/**
    * @export
    * @enum {string}
    */
export enum SolanaRpcRequestOneOf3MethodEnum {
    SIGN_TRANSACTION = 'signTransaction'
}


