/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SolanaAllowedTokensSwapConfig
 */
export interface SolanaAllowedTokensSwapConfig {
    /**
     * 
     * @type {number}
     * @memberof SolanaAllowedTokensSwapConfig
     */
    'max_amount'?: number;
    /**
     * 
     * @type {number}
     * @memberof SolanaAllowedTokensSwapConfig
     */
    'min_amount'?: number;
    /**
     * 
     * @type {number}
     * @memberof SolanaAllowedTokensSwapConfig
     */
    'retain_min_amount'?: number;
    /**
     * 
     * @type {number}
     * @memberof SolanaAllowedTokensSwapConfig
     */
    'slippage_percentage'?: number;
}

