/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * The OpenZeppelin Relayer API provides endpoints for managing, monitoring, and interacting with relayers. It enables developers to relay and manage blockchain transactions across EVM and non-EVM networks, making it ideal for dApps and backend services that require secure and scalable transaction infrastructure.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TransferTransactionRequestParams } from './transfer-transaction-request-params';

/**
 * 
 * @export
 * @interface SolanaRpcRequestOneOf1
 */
export interface SolanaRpcRequestOneOf1 {
    /**
     * 
     * @type {string}
     * @memberof SolanaRpcRequestOneOf1
     */
    'method': SolanaRpcRequestOneOf1MethodEnum;
    /**
     * 
     * @type {TransferTransactionRequestParams}
     * @memberof SolanaRpcRequestOneOf1
     */
    'params': TransferTransactionRequestParams;
}

/**
    * @export
    * @enum {string}
    */
export enum SolanaRpcRequestOneOf1MethodEnum {
    TRANSFER_TRANSACTION = 'transferTransaction'
}


