/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SolanaAccountMeta } from './solana-account-meta';

/**
 * Specification for a Solana instruction
 * @export
 * @interface SolanaInstructionSpec
 */
export interface SolanaInstructionSpec {
    /**
     * Account metadata for the instruction
     * @type {Array<SolanaAccountMeta>}
     * @memberof SolanaInstructionSpec
     */
    'accounts': Array<SolanaAccountMeta>;
    /**
     * Instruction data (base64-encoded)
     * @type {string}
     * @memberof SolanaInstructionSpec
     */
    'data': string;
    /**
     * Program ID (base58-encoded pubkey)
     * @type {string}
     * @memberof SolanaInstructionSpec
     */
    'program_id': string;
}

