/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Account metadata for a Solana instruction
 * @export
 * @interface SolanaAccountMeta
 */
export interface SolanaAccountMeta {
    /**
     * Whether the account is a signer
     * @type {boolean}
     * @memberof SolanaAccountMeta
     */
    'is_signer': boolean;
    /**
     * Whether the account is writable
     * @type {boolean}
     * @memberof SolanaAccountMeta
     */
    'is_writable': boolean;
    /**
     * Account public key (base58-encoded)
     * @type {string}
     * @memberof SolanaAccountMeta
     */
    'pubkey': string;
}

