/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RelayerSolanaSwapConfig } from './relayer-solana-swap-config';
// May contain unused imports in some cases
// @ts-ignore
import type { SolanaAllowedTokensPolicy } from './solana-allowed-tokens-policy';
// May contain unused imports in some cases
// @ts-ignore
import type { SolanaFeePaymentStrategy } from './solana-fee-payment-strategy';

/**
 * Solana policy response model for OpenAPI documentation
 * @export
 * @interface SolanaPolicyResponse
 */
export interface SolanaPolicyResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof SolanaPolicyResponse
     */
    'allowed_accounts'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SolanaPolicyResponse
     */
    'allowed_programs'?: Array<string>;
    /**
     * 
     * @type {Array<SolanaAllowedTokensPolicy>}
     * @memberof SolanaPolicyResponse
     */
    'allowed_tokens'?: Array<SolanaAllowedTokensPolicy>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SolanaPolicyResponse
     */
    'disallowed_accounts'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof SolanaPolicyResponse
     */
    'fee_margin_percentage'?: number;
    /**
     * 
     * @type {SolanaFeePaymentStrategy}
     * @memberof SolanaPolicyResponse
     */
    'fee_payment_strategy'?: SolanaFeePaymentStrategy;
    /**
     * 
     * @type {number}
     * @memberof SolanaPolicyResponse
     */
    'max_allowed_fee_lamports'?: number;
    /**
     * 
     * @type {number}
     * @memberof SolanaPolicyResponse
     */
    'max_signatures'?: number;
    /**
     * 
     * @type {number}
     * @memberof SolanaPolicyResponse
     */
    'max_tx_data_size'?: number;
    /**
     * 
     * @type {number}
     * @memberof SolanaPolicyResponse
     */
    'min_balance'?: number;
    /**
     * 
     * @type {RelayerSolanaSwapConfig}
     * @memberof SolanaPolicyResponse
     */
    'swap_config'?: RelayerSolanaSwapConfig;
}



