/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SolanaAllowedTokensSwapConfig } from './solana-allowed-tokens-swap-config';

/**
 * Configuration for allowed token handling on Solana
 * @export
 * @interface SolanaAllowedTokensPolicy
 */
export interface SolanaAllowedTokensPolicy {
    [key: string]: any;

    /**
     * 
     * @type {number}
     * @memberof SolanaAllowedTokensPolicy
     */
    'decimals'?: number;
    /**
     * 
     * @type {number}
     * @memberof SolanaAllowedTokensPolicy
     */
    'max_allowed_fee'?: number;
    /**
     * 
     * @type {string}
     * @memberof SolanaAllowedTokensPolicy
     */
    'mint': string;
    /**
     * 
     * @type {SolanaAllowedTokensSwapConfig}
     * @memberof SolanaAllowedTokensPolicy
     */
    'swap_config'?: SolanaAllowedTokensSwapConfig;
    /**
     * 
     * @type {string}
     * @memberof SolanaAllowedTokensPolicy
     */
    'symbol'?: string;
}

