/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PrepareTransactionRequestParams } from './prepare-transaction-request-params';

/**
 * 
 * @export
 * @interface SolanaRpcRequestOneOf2
 */
export interface SolanaRpcRequestOneOf2 {
    /**
     * 
     * @type {string}
     * @memberof SolanaRpcRequestOneOf2
     */
    'method': SolanaRpcRequestOneOf2MethodEnum;
    /**
     * 
     * @type {PrepareTransactionRequestParams}
     * @memberof SolanaRpcRequestOneOf2
     */
    'params': PrepareTransactionRequestParams;
}

/**
    * @export
    * @enum {string}
    */
export enum SolanaRpcRequestOneOf2MethodEnum {
    PREPARE_TRANSACTION = 'prepareTransaction'
}


