/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SolanaRpcRequestOneOf6
 */
export interface SolanaRpcRequestOneOf6 {
    /**
     * 
     * @type {string}
     * @memberof SolanaRpcRequestOneOf6
     */
    'method': SolanaRpcRequestOneOf6MethodEnum;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof SolanaRpcRequestOneOf6
     */
    'params': { [key: string]: any; };
}

/**
    * @export
    * @enum {string}
    */
export enum SolanaRpcRequestOneOf6MethodEnum {
    GET_FEATURES_ENABLED = 'getFeaturesEnabled'
}


