/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
export var Speed;
(function (Speed) {
    Speed["FASTEST"] = "fastest";
    Speed["FAST"] = "fast";
    Speed["AVERAGE"] = "average";
    Speed["SAFE_LOW"] = "safeLow";
})(Speed || (Speed = {}));
