/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FeeEstimateRequestParams } from './fee-estimate-request-params';
// May contain unused imports in some cases
// @ts-ignore
import type { OperationSpec } from './operation-spec';

/**
 * @type SponsoredTransactionQuoteRequest
 * Network-agnostic fee estimate request parameters for gasless transactions. Contains network-specific request parameters for fee estimation. The network type is inferred from the relayer\'s network configuration.
 * @export
 */
export type SponsoredTransactionQuoteRequest = FeeEstimateRequestParams;


