/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SolanaPrepareTransactionResult } from './solana-prepare-transaction-result';
// May contain unused imports in some cases
// @ts-ignore
import type { StellarPrepareTransactionResult } from './stellar-prepare-transaction-result';

/**
 * @type SponsoredTransactionBuildResponse
 * Network-agnostic prepare transaction response for gasless transactions. Contains network-specific prepare transaction results.
 * @export
 */
export type SponsoredTransactionBuildResponse = SolanaPrepareTransactionResult | StellarPrepareTransactionResult;


