/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OperationSpec } from './operation-spec';
// May contain unused imports in some cases
// @ts-ignore
import type { SolanaPrepareTransactionRequestParams } from './solana-prepare-transaction-request-params';
// May contain unused imports in some cases
// @ts-ignore
import type { StellarPrepareTransactionRequestParams } from './stellar-prepare-transaction-request-params';

/**
 * @type SponsoredTransactionBuildRequest
 * Network-agnostic prepare transaction request parameters for gasless transactions. Contains network-specific request parameters for preparing transactions with fee payments. The network type is inferred from the relayer\'s network configuration.
 * @export
 */
export type SponsoredTransactionBuildRequest = SolanaPrepareTransactionRequestParams | StellarPrepareTransactionRequestParams;


