/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Stellar policy response model for OpenAPI documentation
 * @export
 * @interface StellarPolicyResponse
 */
export interface StellarPolicyResponse {
    [key: string]: any;

    /**
     * 
     * @type {boolean}
     * @memberof StellarPolicyResponse
     */
    'concurrent_transactions'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof StellarPolicyResponse
     */
    'max_fee'?: number;
    /**
     * 
     * @type {number}
     * @memberof StellarPolicyResponse
     */
    'min_balance'?: number;
    /**
     * 
     * @type {number}
     * @memberof StellarPolicyResponse
     */
    'timeout_seconds'?: number;
}

