/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OperationSpec } from './operation-spec';

/**
 * 
 * @export
 * @interface StellarPrepareTransactionRequestParams
 */
export interface StellarPrepareTransactionRequestParams {
    [key: string]: any;

    /**
     * Asset identifier for fee token
     * @type {string}
     * @memberof StellarPrepareTransactionRequestParams
     */
    'fee_token': string;
    /**
     * Operations array to build transaction from Mutually exclusive with transaction_xdr field
     * @type {Array<OperationSpec>}
     * @memberof StellarPrepareTransactionRequestParams
     */
    'operations'?: Array<OperationSpec>;
    /**
     * Source account address (required when operations are provided) For gasless transactions, this should be the user\'s account address
     * @type {string}
     * @memberof StellarPrepareTransactionRequestParams
     */
    'source_account'?: string;
    /**
     * Pre-built transaction XDR (base64 encoded, signed or unsigned) Mutually exclusive with operations field
     * @type {string}
     * @memberof StellarPrepareTransactionRequestParams
     */
    'transaction_xdr'?: string;
}

