/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StellarAllowedTokensSwapConfig } from './stellar-allowed-tokens-swap-config';
// May contain unused imports in some cases
// @ts-ignore
import type { StellarTokenMetadata } from './stellar-token-metadata';

/**
 * Configuration for allowed token handling on Stellar
 * @export
 * @interface StellarAllowedTokensPolicy
 */
export interface StellarAllowedTokensPolicy {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof StellarAllowedTokensPolicy
     */
    'asset': string;
    /**
     * 
     * @type {number}
     * @memberof StellarAllowedTokensPolicy
     */
    'max_allowed_fee'?: number;
    /**
     * 
     * @type {StellarTokenMetadata}
     * @memberof StellarAllowedTokensPolicy
     */
    'metadata'?: StellarTokenMetadata;
    /**
     * 
     * @type {StellarAllowedTokensSwapConfig}
     * @memberof StellarAllowedTokensPolicy
     */
    'swap_config'?: StellarAllowedTokensSwapConfig;
}

