/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MemoSpec } from './memo-spec';
// May contain unused imports in some cases
// @ts-ignore
import type { OperationSpec } from './operation-spec';

/**
 * 
 * @export
 * @interface StellarTransactionRequest
 */
export interface StellarTransactionRequest {
    /**
     * 
     * @type {MemoSpec}
     * @memberof StellarTransactionRequest
     */
    'memo'?: MemoSpec | null;
    /**
     * 
     * @type {string}
     * @memberof StellarTransactionRequest
     */
    'network': string;
    /**
     * 
     * @type {Array<OperationSpec>}
     * @memberof StellarTransactionRequest
     */
    'operations': Array<OperationSpec>;
    /**
     * 
     * @type {string}
     * @memberof StellarTransactionRequest
     */
    'source_account': string;
    /**
     * 
     * @type {string}
     * @memberof StellarTransactionRequest
     */
    'valid_until'?: string | null;
}

