/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StellarTokenKind } from './stellar-token-kind';

/**
 * 
 * @export
 * @interface StellarTokenMetadata
 */
export interface StellarTokenMetadata {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof StellarTokenMetadata
     */
    'canonical_asset_id': string;
    /**
     * 
     * @type {number}
     * @memberof StellarTokenMetadata
     */
    'decimals': number;
    /**
     * 
     * @type {StellarTokenKind}
     * @memberof StellarTokenMetadata
     */
    'kind': StellarTokenKind;
}

