/* tslint:disable */
 
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StellarTransactionRequest
 */
export interface StellarTransactionRequest {
    /**
     * 
     * @type {string}
     * @memberof StellarTransactionRequest
     */
    'amount': string;
    /**
     * 
     * @type {string}
     * @memberof StellarTransactionRequest
     */
    'asset_code': string;
    /**
     * 
     * @type {string}
     * @memberof StellarTransactionRequest
     */
    'asset_issuer'?: string;
    /**
     * 
     * @type {string}
     * @memberof StellarTransactionRequest
     */
    'destination_account': string;
    /**
     * 
     * @type {number}
     * @memberof StellarTransactionRequest
     */
    'fee': number;
    /**
     * 
     * @type {string}
     * @memberof StellarTransactionRequest
     */
    'memo'?: string;
    /**
     * 
     * @type {string}
     * @memberof StellarTransactionRequest
     */
    'sequence_number': string;
    /**
     * 
     * @type {string}
     * @memberof StellarTransactionRequest
     */
    'source_account': string;
}

