/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StellarTokenKindOneOf1Contract
 */
export interface StellarTokenKindOneOf1Contract {
    /**
     * 
     * @type {string}
     * @memberof StellarTokenKindOneOf1Contract
     */
    'contract_id': string;
}

