/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StellarTokenKindOneOf } from './stellar-token-kind-one-of';
// May contain unused imports in some cases
// @ts-ignore
import type { StellarTokenKindOneOf1 } from './stellar-token-kind-one-of1';
// May contain unused imports in some cases
// @ts-ignore
import type { StellarTokenKindOneOf1Contract } from './stellar-token-kind-one-of1-contract';
// May contain unused imports in some cases
// @ts-ignore
import type { StellarTokenKindOneOfClassic } from './stellar-token-kind-one-of-classic';

/**
 * @type StellarTokenKind
 * @export
 */
export type StellarTokenKind = StellarTokenKindOneOf | StellarTokenKindOneOf1 | string;


