/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * The OpenZeppelin Relayer API provides endpoints for managing, monitoring, and interacting with relayers. It enables developers to relay and manage blockchain transactions across EVM and non-EVM networks, making it ideal for dApps and backend services that require secure and scalable transaction infrastructure.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export enum TransactionStatus {
    CANCELED = 'canceled',
    PENDING = 'pending',
    SENT = 'sent',
    SUBMITTED = 'submitted',
    MINED = 'mined',
    CONFIRMED = 'confirmed',
    FAILED = 'failed',
    EXPIRED = 'expired'
}



