/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Turnkey signer configuration for API requests
 * @export
 * @interface TurnkeySignerRequestConfig
 */
export interface TurnkeySignerRequestConfig {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof TurnkeySignerRequestConfig
     */
    'api_private_key': string;
    /**
     * 
     * @type {string}
     * @memberof TurnkeySignerRequestConfig
     */
    'api_public_key': string;
    /**
     * 
     * @type {string}
     * @memberof TurnkeySignerRequestConfig
     */
    'organization_id': string;
    /**
     * 
     * @type {string}
     * @memberof TurnkeySignerRequestConfig
     */
    'private_key_id': string;
    /**
     * 
     * @type {string}
     * @memberof TurnkeySignerRequestConfig
     */
    'public_key': string;
}

