/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request model for updating an existing plugin. All fields are optional to allow partial updates. Note: `id` and `path` are not updateable after creation.
 * @export
 * @interface UpdatePluginRequest
 */
export interface UpdatePluginRequest {
    [key: string]: any;

    /**
     * Whether to allow GET requests to invoke plugin logic
     * @type {boolean}
     * @memberof UpdatePluginRequest
     */
    'allow_get_invocation'?: boolean;
    /**
     * User-defined configuration accessible to the plugin (must be a JSON object) Use `null` to clear the config
     * @type {{ [key: string]: any; }}
     * @memberof UpdatePluginRequest
     */
    'config'?: { [key: string]: any; };
    /**
     * Whether to include logs in the HTTP response
     * @type {boolean}
     * @memberof UpdatePluginRequest
     */
    'emit_logs'?: boolean;
    /**
     * Whether to include traces in the HTTP response
     * @type {boolean}
     * @memberof UpdatePluginRequest
     */
    'emit_traces'?: boolean;
    /**
     * Whether to forward plugin logs into the relayer\'s tracing output
     * @type {boolean}
     * @memberof UpdatePluginRequest
     */
    'forward_logs'?: boolean;
    /**
     * Whether to return raw plugin response without ApiResponse wrapper
     * @type {boolean}
     * @memberof UpdatePluginRequest
     */
    'raw_response'?: boolean;
    /**
     * Plugin timeout in seconds
     * @type {number}
     * @memberof UpdatePluginRequest
     */
    'timeout'?: number;
}

