/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateRelayerPolicyRequest } from './create-relayer-policy-request';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcConfig } from './rpc-config';

/**
 * 
 * @export
 * @interface UpdateRelayerRequest
 */
export interface UpdateRelayerRequest {
    /**
     * 
     * @type {Array<RpcConfig>}
     * @memberof UpdateRelayerRequest
     */
    'custom_rpc_urls'?: Array<RpcConfig> | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateRelayerRequest
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateRelayerRequest
     */
    'notification_id'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateRelayerRequest
     */
    'paused'?: boolean;
    /**
     * Raw policy JSON - will be validated against relayer\'s network type during application
     * @type {CreateRelayerPolicyRequest}
     * @memberof UpdateRelayerRequest
     */
    'policies'?: CreateRelayerPolicyRequest | null;
}

