/* tslint:disable */
/* eslint-disable */
/**
 * OpenZeppelin Relayer API
 * OpenZeppelin Relayer API
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WasmSourceOneOf } from './wasm-source-one-of';
// May contain unused imports in some cases
// @ts-ignore
import type { WasmSourceOneOf1 } from './wasm-source-one-of1';

/**
 * @type WasmSource
 * Represents different ways to provide WASM code
 * @export
 */
export type WasmSource = WasmSourceOneOf | WasmSourceOneOf1;


