---
name: Pre-requisites
description: |
  Setup Pre-requisites

runs:
  using: composite
  runs-on: ubuntu-latest
  steps:
    - uses: actions/create-github-app-token@af35edadc00be37caa72ed9f3e6d5f7801bfdf09 # v1.11.7
      id: gh-app-token
      with:
        app-id: ${{ vars.GH_APP_ID }}
        private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

    - name: Checkout Repo
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.5.4
        with:
          token: ${{ steps.gh-app-token.outputs.token }}
          persist-credentials: false
    - uses: pnpm/action-setup@v4
      with:
        version: 9
        run_install: false

    - name: Use node@20
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: 20.11.1
        cache: 'pnpm'

    - name: Install dependencies
      run: |
        pnpm install-deps
      shell: bash
