---
name: Pre-requisites
description: |
  Setup Pre-requisites

inputs:
  gh-app-id:
    required: true
  gh-app-private-key:
    required: true

runs:
  using: composite
  steps:
    - name: Checkout Repo
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.5.4
        with:
          persist-credentials: false

    - uses: pnpm/action-setup@v4
      with:
        version: 9
        run_install: false

    - name: Use node@20
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: 20.11.1
        cache: 'pnpm'

    - name: Install dependencies
      run: |
        pnpm install-deps
      shell: bash
