name: Release Drafter
on:
 push:
   branches:
     - main
jobs:
 update_release_draft:
   runs-on: ubuntu-24.04
   steps:
     - uses: release-drafter/release-drafter@6df64e4ba4842c203c604c1f45246c5863410adb
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
