name: Version Package

on:
  workflow_dispatch: {}
  push:
    branches:
      - refactor-release-flow

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@af35edadc00be37caa72ed9f3e6d5f7801bfdf09 # v1.11.7
        id: gh-app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout Repo
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.5.4
        with:
          token: ${{ steps.gh-app-token.outputs.token }}

      - name: Prepare pre-requisites
        uses: ./.github/actions/prepare

      - name: Create Release Pull Request
        uses: changesets/action@3de3850952bec538fde60aac71731376e57b9b57 # v1.4.8
        with:
          setupGitUser: false
          version: pnpm ci:version
          title: "ci: update the version packages"
        env:
          GITHUB_TOKEN: ${{ steps.gh-app-token.outputs.token }}

      - name: Update the lock file
        run: pnpm install --lockfile-only
        shell: bash

      - name: Set up upstream branch
        run: |
          if git show-ref --verify --quiet refs/remotes/origin/changeset-release/main; then
            git push --set-upstream origin changeset-release/main
          else
            echo "Skipping because the branch changeset-release/main does not exist..."
          fi
        shell: bash

      - name: Commit pnpm-lock.yaml file changes
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38
        with:
          commit-message: "🤖 chore: Update the pnpm-lock.yaml file"
          title: "chore: 🤖 [Automated PR] Update the pnpm-lock.yaml file"
          token: ${{ steps.gh-app-token.outputs.token }}
          sign-commits: true
          body: |
            This PR updates the pnpm-lock.yaml file
